'use strict';
const {ShareSignaling}=require('./share-signaling.cjs');
const crypto=require('node:crypto'),{BrowserSession}=require('./browser-session.cjs');
const LIMITS=Object.freeze({rooms:16,pendingInputs:256,inputLifetimeMs:3000,acceptedInputs:1024});
function error(message,status=403){const e=Error(message);e.status=status;return e;}
class BrowserRooms {
 constructor({now=Date.now,access,active,profile,fixtureOrigin=null}){this.now=now;this.access=access;this.active=active;this.profile=profile;this.fixtureOrigin=fixtureOrigin;this.rooms=new Map();this.pending=new Map();this.accepted=new Map();this.applied=new Map();this.signaling=new ShareSignaling({now});this.connections=new Map();}
 requireChat(chat,actor){if(!this.access(chat,actor))throw error('Browser chat access denied');if(!this.active(chat))throw error('Browser chat has ended',409);}
 prune(){for(const room of [...this.rooms.values()]){if(!this.active(room.chatId)||!this.access(room.chatId,room.hostId)){room.end('Browser host or chat unavailable');}else{for(const actor of [...room.members.keys()])if(!this.access(room.chatId,actor))room.remove(actor);room.prune();}if(room.closed){const call=this.connections.get(room.id);if(call)this.signaling.end(call,null,'Browser session ended');this.connections.delete(room.id);this.rooms.delete(room.id);}}for(const id of this.applied.keys())if(!this.rooms.has(id))this.applied.delete(id);for(const map of [this.pending,this.accepted])for(const [id,item]of map)if(item.expiresAt<=this.now()||!this.rooms.has(item.roomId))map.delete(id);}
 get(id,actor){this.prune();const room=this.rooms.get(id);if(!room)throw error('Browser session unavailable',409);this.requireChat(room.chatId,actor);room.member(actor);room.heartbeat(actor);return room;}
 list(chat,actor){this.requireChat(chat,actor);this.prune();return{rooms:[...this.rooms.values()].filter(r=>r.chatId===chat).map(r=>({id:r.id,hostId:r.hostId,ownerId:r.ownerId,participants:r.members.size}))};}
 start(chat,actor){this.requireChat(chat,actor);this.prune();const existing=[...this.rooms.values()].find(r=>r.chatId===chat);if(existing){if(existing.hostId!==actor)throw error('This chat already has a shared browser',409);existing.heartbeat(actor);return existing.snapshot(actor);}if(this.rooms.size>=LIMITS.rooms)throw error('Browser session capacity reached',429);if([...this.rooms.values()].some(r=>r.members.has(actor)))throw error('Already participating in a shared browser',409);const room=new BrowserSession({chatId:chat,creator:{userId:actor,name:this.profile(actor)},now:this.now,fixtureOrigin:this.fixtureOrigin});this.rooms.set(room.id,room);return room.snapshot(actor);}
 join(id,actor){this.prune();const room=this.rooms.get(id);if(!room)throw error('Browser session unavailable',409);this.requireChat(room.chatId,actor);if([...this.rooms.values()].some(r=>r.id!==id&&r.members.has(actor)))throw error('Already participating in a shared browser',409);if(!room.members.has(actor)&&room.members.size>=2)throw error('This browser supports two people',409);room.join({userId:actor,name:this.profile(actor)});room.heartbeat(actor);return room.snapshot(actor);}
 connection(id,actor){const room=this.get(id,actor),peer=[...room.members.keys()].find(id=>id!==room.hostId);if(!peer)return null;let callId=this.connections.get(id);if(!callId||!this.signaling.callFor(callId,actor)){callId=this.signaling.start(room.chatId,room.hostId,peer).id;this.connections.set(id,callId);}return{callId,hostId:room.hostId,peerId:actor===room.hostId?peer:room.hostId,isHost:actor===room.hostId,iceServers:this.fixtureOrigin?[]:[{urls:'stun:stun.cloudflare.com:3478'}],turnReady:false};}
 signals(id,actor,after){if(!Number.isSafeInteger(after)||after<0)throw error('Invalid browser signal cursor',400);const connection=this.connection(id,actor);if(!connection)return{events:[],cursor:after};const room=this.get(id,actor);this.signaling.send(connection.callId,room.chatId,actor,'heartbeat');const events=this.signaling.eventsFor(actor,after).filter(e=>e.callId===connection.callId);return{events,cursor:events.at(-1)?.seq||after};}
 signal(id,actor,{kind,payload}){const room=this.get(id,actor),connection=this.connection(id,actor);if(!connection)throw error('Browser peer unavailable',409);this.signaling.send(connection.callId,room.chatId,actor,kind,payload);return{ok:true};}
 snapshot(id,actor){return this.get(id,actor).snapshot(actor);}
 act(id,actor,command){const room=this.get(id,actor);if(command.target)this.requireChat(room.chatId,command.target);return room.act(actor,command);}
 end(id,actor){const room=this.get(id,actor);room.owner(actor);room.end('Shared browser ended');this.prune();return{ended:true};}
 leave(id,actor){const room=this.get(id,actor);room.remove(actor);this.prune();return{left:true};}
 queue(id,actor,body){const room=this.get(id,actor);if(typeof body.envelope!=='string'||body.envelope.length<40||body.envelope.length>3072||!/^[a-z0-9+/]+=*$/i.test(body.envelope))throw error('Invalid encrypted browser input',400);room.authorizeInput(actor,body);room.inputBudget(actor);if(this.pending.size>=LIMITS.pendingInputs)throw error('Browser input queue full',429);const ticket={id:crypto.randomUUID(),roomId:id,actor,epoch:body.epoch,tabId:body.tabId,tabEpoch:body.tabEpoch,envelope:body.envelope,sequence:++room.sequence,expiresAt:this.now()+LIMITS.inputLifetimeMs};this.pending.set(ticket.id,ticket);return{id:ticket.id,sequence:ticket.sequence};}
 host(id,actor){const room=this.get(id,actor);if(actor!==room.hostId)throw error('Browser host required');return room;}
 pendingFor(id,actor){const room=this.host(id,actor);return{state:room.snapshot(actor),inputs:[...this.pending.values()].filter(t=>t.roomId===id).sort((a,b)=>a.sequence-b.sequence).slice(0,64).map(t=>({id:t.id,sequence:t.sequence}))};}
 accept(id,actor,ticketId){const room=this.host(id,actor),ticket=this.pending.get(ticketId)||this.accepted.get(ticketId);if(!ticket||ticket.roomId!==id||ticket.expiresAt<=this.now())throw error('Browser input expired',409);room.authorizeInput(ticket.actor,ticket);if(this.pending.has(ticketId)){if(this.accepted.size>=LIMITS.acceptedInputs)throw error('Browser input acknowledgements full',429);if(ticket.sequence<=(this.applied.get(id)||0))throw error('Browser input order changed',409);this.pending.delete(ticketId);this.accepted.set(ticketId,ticket);this.applied.set(id,ticket.sequence);}return{state:room.snapshot(actor),input:{...ticket}};}
 document(id,actor,metadata){return this.host(id,actor).document(actor,metadata);}
 capture(id,actor,tabId,metadata){const room=this.host(id,actor);return room.capture(actor,tabId,metadata);}
 close(){for(const room of this.rooms.values())room.end('Relay closed');this.rooms.clear();this.pending.clear();this.accepted.clear();this.applied.clear();this.signaling.close();this.connections.clear();}
}
module.exports={BrowserRooms,LIMITS};
