'use strict';
const crypto=require('node:crypto'),S=require('./shared-task-schedule.cjs'),{keys,seal,open}=require('./shared-protocol.cjs');
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
const fail=(message,status=409)=>{const e=new Error(message);e.status=status;throw e;};
const requireId=value=>{if(!UUID.test(value||''))fail('Invalid task identifier',400);return value;};
function createCollaborationStore(db,{secret,now=Date.now,capacity=()=>{},canAccess,ended,audience,admission=()=>0,historyShared=(chat,user)=>admission(chat,user)===0,canManage,profileName=()=> 'Chat member'}){
 const key=keys(secret).key;const scheduleErrors=new Map();
 db.exec("CREATE TABLE IF NOT EXISTS fw_task_lists(id TEXT PRIMARY KEY,chat_id TEXT NOT NULL,owner_id TEXT NOT NULL,revision INTEGER NOT NULL,state TEXT NOT NULL,created_at INTEGER NOT NULL,admitted_seq INTEGER NOT NULL,deleted INTEGER NOT NULL DEFAULT 0); CREATE TABLE IF NOT EXISTS fw_task_members(list_id TEXT,user_id TEXT,admission TEXT NOT NULL DEFAULT '',PRIMARY KEY(list_id,user_id)); CREATE TABLE IF NOT EXISTS fw_task_versions(chat_id TEXT PRIMARY KEY,version INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS fw_task_actions(id TEXT PRIMARY KEY,actor_id TEXT NOT NULL,chat_id TEXT NOT NULL,digest TEXT NOT NULL,result TEXT NOT NULL); CREATE TABLE IF NOT EXISTS fw_away(user_id TEXT PRIMARY KEY,enabled INTEGER NOT NULL,text_frame TEXT NOT NULL,period INTEGER NOT NULL,activated_at INTEGER NOT NULL,activated_seq INTEGER NOT NULL,version INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS fw_away_actions(id TEXT PRIMARY KEY,actor_id TEXT NOT NULL,digest TEXT NOT NULL); CREATE TABLE IF NOT EXISTS fw_away_replies(user_id TEXT,chat_id TEXT,period INTEGER,message_id TEXT UNIQUE NOT NULL,trigger_id TEXT NOT NULL,PRIMARY KEY(user_id,chat_id,period));");
 // Legacy grants lack proof of their original admission. Keep their rows/data, but
 // only an explicit full-history policy can authorize them until newly granted.
 if(!db.prepare('PRAGMA table_info(fw_task_members)').all().some(c=>c.name==='admission'))db.exec("ALTER TABLE fw_task_members ADD COLUMN admission TEXT NOT NULL DEFAULT ''");
 if(!db.prepare('PRAGMA table_info(messages)').all().some(c=>c.name==='message_kind'))db.exec("ALTER TABLE messages ADD COLUMN message_kind TEXT NOT NULL DEFAULT 'human'");
 function access(chat,user,write=false){if(!canAccess(chat,user))fail('Chat access denied',403);if(write&&ended(chat))fail('Chat has ended');}
 function currentSeq(){return db.prepare('SELECT COALESCE(MAX(seq),0) AS n FROM messages').get().n;}
 function encode(value){return seal(Buffer.from(JSON.stringify(value)),key).toString('base64');}
 function decode(frame){if(typeof frame!=='string'||frame.length>2048||!/^[A-Za-z0-9+/]+={0,2}$/.test(frame))fail('Invalid encrypted task text',400);try{return JSON.parse(open(Buffer.from(frame,'base64'),key));}catch{fail('Encrypted task text failed validation',422);}}
 function label(frame,listId,itemId=null,max=240){const text=decode(frame);if(text.v!==1||text.listId!==listId||(text.itemId||null)!==itemId||typeof text.text!=='string'||!text.text.trim()||text.text.length>max||Object.keys(text).some(k=>!['v','listId','itemId','text'].includes(k)))fail('Task text does not match its list or item',422);return text.text;}
 function version(chat){return db.prepare('SELECT version FROM fw_task_versions WHERE chat_id=?').get(chat)?.version||0;}
 function bump(chat){db.prepare('INSERT INTO fw_task_versions VALUES (?,1) ON CONFLICT(chat_id) DO UPDATE SET version=version+1').run(chat);}
 function visible(row,user){
  if(!canAccess(row.chat_id,user))return false;
  if(historyShared(row.chat_id,user)===true)return true;
  const current=admission(row.chat_id,user),grant=db.prepare('SELECT admission FROM fw_task_members WHERE list_id=? AND user_id=?').get(row.id,user);
  return current!==null&&current!==undefined&&!!grant&&grant.admission===String(current);
 }
 function grant(listId,chat,user){const current=admission(chat,user);if(!canAccess(chat,user)||current===null||current===undefined)fail('Chat access denied',403);db.prepare('INSERT INTO fw_task_members(list_id,user_id,admission) VALUES (?,?,?)').run(listId,user,String(current));}
 function accessVersion(){return version('$admissions');}
 function accessChanged(){bump('$admissions');}
 function admissionChanged(chat){bump(chat);accessChanged();}
 function revoke(chat,user){db.prepare('DELETE FROM fw_task_members WHERE user_id=? AND list_id IN (SELECT id FROM fw_task_lists WHERE chat_id=?)').run(user,chat);admissionChanged(chat);}
 function revokeMember(user){const chats=new Set(db.prepare('SELECT DISTINCT l.chat_id FROM fw_task_lists l JOIN fw_task_members m ON m.list_id=l.id WHERE m.user_id=?').all(user).map(row=>row.chat_id));if(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='chat_members'").get())for(const row of db.prepare('SELECT chat_id FROM chat_members WHERE user_id=?').all(user))chats.add(row.chat_id);db.prepare('DELETE FROM fw_task_members WHERE user_id=?').run(user);for(const chat of chats)bump(chat);bump('$admissions');}
 function stateFor(row){try{if(typeof row.state!=='string'||row.state.length>2*1024*1024)throw Error();const state=JSON.parse(row.state);if(state.v!==1||!Array.isArray(state.items)||state.items.length>100||!Array.isArray(state.history)||state.history.length>2000)throw Error();label(state.titleFrame,row.id,null,64);const ids=new Set();for(const item of state.items){requireId(item.id);if(ids.has(item.id)||typeof item.done!=='boolean'||!Number.isSafeInteger(item.revision)||item.revision<1||!Number.isSafeInteger(item.scheduleGeneration)||item.scheduleGeneration<0||item.deleted!==undefined&&typeof item.deleted!=='boolean')throw Error();ids.add(item.id);label(item.labelFrame,row.id,item.id);S.validate(item.schedule);if(item.completedBy!==null)requireId(item.completedBy);if(item.completedAt!==null&&(!Number.isSafeInteger(item.completedAt)||item.completedAt<0)||item.done!==!!item.completedBy||item.done!==Number.isSafeInteger(item.completedAt))throw Error();if(item.nextResetAt!==null&&(!Number.isSafeInteger(item.nextResetAt)||item.nextResetAt<0)||(!item.schedule.enabled||item.deleted)&&item.nextResetAt!==null)throw Error();}const events=new Set();for(const event of state.history){requireId(event.id);if(events.has(event.id)||!Number.isSafeInteger(event.time)||event.time<0||!['list-created','list-renamed','list-moved-in','list-moved-out','list-copied','list-shared-copy','item-created','item-edited','item-deleted','completed','unchecked','scheduled-reset'].includes(event.type))throw Error();events.add(event.id);if(event.actorId!==null){requireId(event.actorId);const actor=decode(event.actorFrame);if(actor.v!==1||actor.userId!==event.actorId||typeof actor.name!=='string'||actor.name.length>32)throw Error();}else if(event.type!=='scheduled-reset')throw Error();if(event.labelFrame)label(event.labelFrame,event.sourceListId||row.id,event.sourceItemId||event.itemId);}return state;}catch{fail('Task history failed validation; editing is blocked',422);}}
 function get(id,chat,user){const row=db.prepare('SELECT * FROM fw_task_lists WHERE id=? AND chat_id=? AND deleted=0').get(id,chat);if(!row||!visible(row,user))fail('Task list unavailable',403);return{row,state:stateFor(row)};}
 function history(state,type,user,extra={}){if(state.history.length>=2000)fail('This list has reached its history limit. Saved history is preserved. Create another list.');const actorFrame=user?encode({v:1,userId:user,name:profileName(user)}):null;state.history.push({id:crypto.randomUUID(),type,actorId:user||null,actorFrame,time:now(),...extra});}
 function save(row,state){const bytes=JSON.stringify(state);capacity(Buffer.byteLength(bytes)*2+8192);db.prepare('UPDATE fw_task_lists SET state=?,revision=revision+1 WHERE id=?').run(bytes,row.id);bump(row.chat_id);}
 function summary(row,state){return{id:row.id,chatId:row.chat_id,ownerId:row.owner_id,revision:row.revision,titleFrame:state.titleFrame,items:state.items.filter(i=>!i.deleted),historyCount:state.history.length,schedulingError:state.schedulingError||scheduleErrors.get(row.chat_id)||''};}
 function list(chat,user){access(chat,user);return{version:version(chat),admission:String(admission(chat,user)),accessVersion:accessVersion(),readOnly:ended(chat),lists:db.prepare('SELECT * FROM fw_task_lists WHERE chat_id=? AND deleted=0 ORDER BY created_at,id').all(chat).filter(row=>visible(row,user)).map(row=>summary(row,stateFor(row)))};}
 function readHistory(chat,user,id,offset=0){access(chat,user);if(!Number.isSafeInteger(offset)||offset<0)fail('Invalid task history position',400);const {state}=get(requireId(id),chat,user);return{history:state.history.slice(offset,offset+100),total:state.history.length,offset};}
 function role(chat,user){access(chat,user,true);return canManage(chat,user);}
 function transferAccess(chat,user,body){access(chat,user,true);access(body.destinationChatId,user,true);const destination=audience(body.destinationChatId).slice().sort();if(!['copy','move'].includes(body.mode)||!Array.isArray(body.destinationMembers)||JSON.stringify([...body.destinationMembers].sort())!==JSON.stringify(destination))fail('Destination audience changed. Review the people and try again.');if(!role(body.destinationChatId,user))fail('Destination chat owner or moderator required',403);return destination;}
 function act(chat,user,body){
  access(chat,user,true);if(!body||typeof body!=='object'||Array.isArray(body))fail('Invalid task action',400);requireId(body.actionId);const digest=crypto.createHash('sha256').update(JSON.stringify(body)).digest('hex'),prior=db.prepare('SELECT * FROM fw_task_actions WHERE id=?').get(body.actionId);
  if(body.type==='transfer')transferAccess(chat,user,body);
  if(prior){
   if(prior.actor_id!==user||prior.chat_id!==chat||prior.digest!==digest)fail('Conflicting task retry');
   // A durable receipt proves an old action committed, not that its actor retains
   // access now. Include a moved source tombstone so valid retries still converge.
   const row=db.prepare('SELECT * FROM fw_task_lists WHERE id=? AND chat_id=?').get(requireId(body.listId),chat);
   if(!row||!visible(row,user))fail('Task list unavailable',403);
   if(body.type==='transfer'&&row.owner_id!==user&&!role(chat,user))fail('List owner or chat moderator required',403);
   return{...JSON.parse(prior.result),replayed:true};
  }
  capacity(8192);db.exec('BEGIN IMMEDIATE');try{let result;
   if(body.type==='create'){requireId(body.listId);label(body.titleFrame,body.listId,null,64);if(db.prepare('SELECT COUNT(*) AS n FROM fw_task_lists WHERE chat_id=? AND deleted=0').get(chat).n>=20)fail('This chat has 20 task lists');const state={v:1,titleFrame:body.titleFrame,items:[],history:[]};history(state,'list-created',user,{actionId:body.actionId});db.prepare('INSERT INTO fw_task_lists VALUES (?,?,?,?,?,?,?,0)').run(body.listId,chat,user,1,JSON.stringify(state),now(),currentSeq());for(const member of audience(chat))grant(body.listId,chat,member);bump(chat);result={listId:body.listId};}
   else{const {row,state}=get(requireId(body.listId),chat,user);
    if(['rename','transfer'].includes(body.type)&&body.expectedRevision!==row.revision)fail('This list changed. Review the latest version.');
    if(body.type==='rename'){label(body.titleFrame,row.id,null,64);state.titleFrame=body.titleFrame;history(state,'list-renamed',user,{actionId:body.actionId});save(row,state);}
    else if(body.type==='transfer'){if(row.owner_id!==user&&!role(chat,user))fail('List owner or chat moderator required',403);const members=transferAccess(chat,user,body),newId=requireId(body.newListId);if(body.destinationChatId===chat)fail('Choose another chat');if(db.prepare('SELECT COUNT(*) AS n FROM fw_task_lists WHERE chat_id=? AND deleted=0').get(body.destinationChatId).n>=20)fail('Destination chat has 20 task lists');const moved=structuredClone(state),ids=new Map();moved.titleFrame=encode({v:1,listId:newId,text:label(state.titleFrame,row.id,null,64)});for(const item of moved.items){const id=crypto.randomUUID();ids.set(item.id,id);item.labelFrame=encode({v:1,listId:newId,itemId:id,text:label(item.labelFrame,row.id,item.id)});item.id=id;item.revision=1;}for(const h of moved.history){h.sourceListId=h.sourceListId||row.id;if(h.itemId){h.sourceItemId=h.sourceItemId||h.itemId;h.itemId=ids.get(h.itemId)||h.itemId;}}history(moved,body.mode==='move'?'list-moved-in':'list-copied',user,{actionId:body.actionId,sourceListId:row.id});capacity(Buffer.byteLength(JSON.stringify(moved))*3+8192);db.prepare('INSERT INTO fw_task_lists VALUES (?,?,?,?,?,?,?,0)').run(newId,body.destinationChatId,user,1,JSON.stringify(moved),now(),currentSeq());for(const member of members)grant(newId,body.destinationChatId,member);if(body.mode==='move'){history(state,'list-moved-out',user,{actionId:body.actionId,destinationChatId:body.destinationChatId});save(row,state);db.prepare('UPDATE fw_task_lists SET deleted=1 WHERE id=?').run(row.id);}else history(state,'list-shared-copy',user,{actionId:body.actionId,destinationChatId:body.destinationChatId});if(body.mode==='copy')save(row,state);bump(body.destinationChatId);result={listId:newId,destinationChatId:body.destinationChatId};}
    else{let item=state.items.find(i=>i.id===body.itemId&&!i.deleted);
     if(body.type==='item-create'){requireId(body.itemId);if(state.items.some(i=>i.id===body.itemId)||state.items.length>=100)fail('Task item limit or reused identifier');label(body.labelFrame,row.id,body.itemId);item={id:body.itemId,labelFrame:body.labelFrame,done:false,completedBy:null,completedAt:null,revision:1,schedule:{mode:'none',enabled:false},scheduleGeneration:0,nextResetAt:null};state.items.push(item);history(state,'item-created',user,{itemId:item.id,labelFrame:item.labelFrame,actionId:body.actionId});}
     else{if(!item||body.expectedItemRevision!==item.revision)fail('This task changed. Review the latest version.');
      if(body.type==='complete'){if(typeof body.done!=='boolean')fail('Choose a completion state',400);if(item.done!==body.done){item.done=body.done;item.completedBy=body.done?user:null;item.completedAt=body.done?now():null;history(state,body.done?'completed':'unchecked',user,{itemId:item.id,labelFrame:item.labelFrame,actionId:body.actionId});}}
      else if(body.type==='item-edit'){label(body.labelFrame,row.id,item.id);item.labelFrame=body.labelFrame;if(body.schedule!==undefined){const schedule=S.validate(body.schedule);if(JSON.stringify(schedule)!==JSON.stringify(item.schedule)){const due=S.next(schedule,now());if(schedule.mode==='once'&&schedule.enabled&&due<=now())fail('Choose a future one-time reset');item.schedule=schedule;item.scheduleGeneration++;item.nextResetAt=due;}}history(state,'item-edited',user,{itemId:item.id,labelFrame:item.labelFrame,actionId:body.actionId});}
      else if(body.type==='item-delete'){item.deleted=true;item.nextResetAt=null;history(state,'item-deleted',user,{itemId:item.id,labelFrame:item.labelFrame,actionId:body.actionId});}
      else fail('Unknown task action',400);item.revision++;
     }save(row,state);
    }result||={listId:row.id};
   }
   db.prepare('INSERT INTO fw_task_actions VALUES (?,?,?,?,?)').run(body.actionId,user,chat,digest,JSON.stringify(result));db.exec('COMMIT');return result;
  }catch(error){db.exec('ROLLBACK');throw error;}
 }
 function processDue(){let changed=false;scheduleErrors.clear();for(const row of db.prepare('SELECT * FROM fw_task_lists WHERE deleted=0').all()){if(ended(row.chat_id))continue;let state;try{state=JSON.parse(row.state);if(state.v!==1||!Array.isArray(state.items)||state.items.length>100)throw Error('Task history failed validation; editing is blocked');if(state.schedulingError)continue;const due=state.items.filter(i=>!i.deleted&&i.schedule?.enabled&&Number.isFinite(i.nextResetAt)&&i.nextResetAt<=now());if(!due.length)continue;stateFor(row);db.exec('BEGIN IMMEDIATE');try{for(const item of due){const scheduledFor=item.nextResetAt,resetKey=item.scheduleGeneration+'|'+scheduledFor;if(item.done){history(state,'scheduled-reset',null,{itemId:item.id,labelFrame:item.labelFrame,scheduledFor,resetKey,previousCompletedBy:item.completedBy,previousCompletedAt:item.completedAt});item.done=false;item.completedBy=null;item.completedAt=null;}if(item.schedule.mode==='once')item.schedule={...item.schedule,enabled:false};item.nextResetAt=S.next(item.schedule,now());item.revision++;}save(row,state);db.exec('COMMIT');changed=true;}catch(error){db.exec('ROLLBACK');throw error;}}catch(error){scheduleErrors.set(row.chat_id,error.status===507?'Scheduled reset waiting for storage space.':error.message);}}
  return changed;
 }
 function away(user){const row=db.prepare('SELECT * FROM fw_away WHERE user_id=?').get(user);return row?{userId:user,enabled:!!row.enabled,frame:row.text_frame,period:row.period,activatedAt:row.activated_at,activatedSeq:row.activated_seq,version:row.version}:{userId:user,enabled:false,frame:null,period:0,activatedAt:0,activatedSeq:0,version:0};}
 function awayText(frame,user){const value=decode(frame);if(value.v!==1||value.userId!==user||typeof value.text!=='string'||value.text.length>240||Object.keys(value).some(k=>!['v','userId','text'].includes(k)))fail('Invalid Away message',400);return value.text.trim();}
 function setAway(user,body){if(!body||typeof body.enabled!=='boolean')fail('Choose an Away state',400);const digest=crypto.createHash('sha256').update(JSON.stringify(body)).digest('hex');if(body.actionId){requireId(body.actionId);const prior=db.prepare('SELECT * FROM fw_away_actions WHERE id=?').get(body.actionId);if(prior){if(prior.actor_id!==user||prior.digest!==digest)fail('Conflicting Away retry');return away(user);}}const text=awayText(body.frame,user),old=away(user);if(body.enabled&&!text)fail('Enter an Away message');if(body.expectedVersion!==old.version)fail('Away settings changed on another device. Review and try again.');const activated=body.enabled&&!old.enabled,period=old.period+(activated?1:0);capacity(body.frame.length*3+8192);db.exec('BEGIN IMMEDIATE');try{db.prepare('INSERT INTO fw_away VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET enabled=excluded.enabled,text_frame=excluded.text_frame,period=excluded.period,activated_at=excluded.activated_at,activated_seq=excluded.activated_seq,version=excluded.version').run(user,body.enabled?1:0,body.frame,period,activated?now():old.activatedAt,activated?currentSeq():old.activatedSeq,old.version+1);if(body.actionId)db.prepare('INSERT INTO fw_away_actions VALUES (?,?,?)').run(body.actionId,user,digest);db.exec('COMMIT');return away(user);}catch(error){db.exec('ROLLBACK');throw error;}}

 function awayFor(chat,user){access(chat,user);return audience(chat).map(id=>away(id)).filter(row=>row.enabled||row.userId===user);}
 // Called inside the human-message insertion transaction. A reply and its durable
 // per-chat activation claim commit together, even while every Away client is offline.
 function replyToHuman(chat,human){access(chat,human.userId,true);for(const user of audience(chat)){if(user===human.userId||!canAccess(chat,user))continue;const status=away(user);if(!status.enabled||human.seq<=status.activatedSeq||human.time<status.activatedAt||db.prepare('SELECT 1 FROM fw_away_replies WHERE user_id=? AND chat_id=? AND period=?').get(user,chat,status.period))continue;let body;try{body=awayText(status.frame,user);}catch{continue;}const id=crypto.randomUUID(),message={id,userId:user,name:profileName(user),body,time:new Date(now()).toISOString(),language:'en',autoReply:{v:1,period:status.period,triggerId:human.id}},frame=encode(message);try{capacity(frame.length*3+8192);}catch(error){if(error.status===507)continue;throw error;}db.prepare("INSERT INTO messages(id,frame,user_id,received_at,chat_id,message_kind) VALUES (?,?,?,?,?,'away')").run(id,frame,user,now(),chat);db.prepare('INSERT INTO fw_away_replies VALUES (?,?,?,?,?)').run(user,chat,status.period,id,human.id);}}
 return{list,history:readHistory,act,version,processDue,away,setAway,awayFor,replyToHuman,revoke,revokeMember,accessVersion,admissionChanged,accessChanged};
}
module.exports={createCollaborationStore};
