const crypto=require('node:crypto');
const {validate,footprint}=require('./fleet-geometry.cjs');
function initial(ids,starter=ids[crypto.randomInt(2)]){return {revision:0,phase:'setup',starter,turn:null,fleets:Object.fromEntries(ids.map(id=>[id,[]])),ready:Object.fromEntries(ids.map(id=>[id,false])),shots:[],winner:null,ending:null,last:null,rematch:[],rematchId:null};}
function publicShot(shot){const out={actor:shot.actor,cell:shot.cell,result:shot.result};if(shot.result==='sunk')out.sunk={id:shot.sunk.id,cells:[...shot.sunk.cells]};return out;}
function fleetView(state,user,ids){if(!ids.includes(user))throw new Error('Game access denied');const other=ids.find(id=>id!==user);return {revision:state.revision,phase:state.phase,turn:state.turn,ready:Object.fromEntries(ids.map(id=>[id,!!state.ready[id]])),fleet:validate(state.fleets[user]||[]),shots:state.shots.map(publicShot),winner:state.winner,ending:state.ending,last:state.last?publicShot(state.last):null,rematch:state.rematch.filter(id=>ids.includes(id)),rematchId:state.rematchId,...(state.ending==='victory'?{opponentFleet:validate(state.fleets[other],true)}:{})};}
function play(state,ids,actor,body){if(!ids.includes(actor))throw new Error('Game access denied');const next=structuredClone(state),other=ids.find(id=>id!==actor);
 if(body.action==='fleet'||body.action==='ready'){if(next.phase!=='setup')throw new Error('Fleet is fixed once battle begins');next.fleets[actor]=validate(body.fleet,body.action==='ready');next.ready[actor]=body.action==='ready';if(ids.every(id=>next.ready[id])){next.phase='battle';next.turn=next.starter;}}
 else if(body.action==='fire'){if(next.phase!=='battle')throw new Error('Battle is not active');if(next.turn!==actor)throw new Error('Wait for your turn');const cell=body.cell;if(!Number.isInteger(cell)||cell<0||cell>=100)throw new Error('Choose a coordinate on the board');if(next.shots.some(s=>s.actor===actor&&s.cell===cell))throw new Error('That coordinate has already been fired at');const ship=next.fleets[other].find(s=>footprint(s).includes(cell));const shot={actor,cell,result:ship?'hit':'miss'};next.shots.push(shot);if(ship){const cells=footprint(ship);if(cells.every(c=>next.shots.some(s=>s.actor===actor&&s.cell===c))){shot.result='sunk';shot.sunk={id:ship.id,cells};}if(next.fleets[other].every(s=>footprint(s).every(c=>next.shots.some(t=>t.actor===actor&&t.cell===c)))){next.phase='finished';next.winner=actor;next.ending='victory';}}next.last=shot;next.turn=next.phase==='battle'?other:null;}
 else if(body.action==='resign'){if(!['setup','battle'].includes(next.phase))throw new Error('Game has ended');next.phase='finished';next.winner=other;next.ending='resigned';next.turn=null;}
 else if(body.action==='rematch'){if(next.phase!=='finished')throw new Error('Finish this game first');if(next.rematch.includes(actor))throw new Error('Rematch already requested');next.rematch.push(actor);}
 else throw new Error('Invalid Fleet Duel action');next.revision++;return next;
}
function createFleetStore(db,{now=Date.now,canAccessChat,onEvent=()=>{}}){
 db.exec('CREATE TABLE IF NOT EXISTS fw_fleet_actions(game_id TEXT NOT NULL,actor_id TEXT NOT NULL,action_id TEXT NOT NULL,digest TEXT NOT NULL,response TEXT NOT NULL,PRIMARY KEY(game_id,actor_id,action_id));');
 const row=id=>db.prepare('SELECT * FROM fw_games WHERE id=?').get(id),players=id=>db.prepare('SELECT user_id,accepted FROM fw_game_players WHERE game_id=? ORDER BY rowid').all(id);
 const requirePlayer=(id,user)=>{const g=row(id);if(!g||g.kind!=='fleet'||!players(id).some(p=>p.user_id===user)||!canAccessChat(g.chat_id,user))throw new Error('Game access denied');return g;};
 const tx=work=>{db.exec('BEGIN IMMEDIATE');let value;try{value=work();db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}onEvent();return value;};
 const record=(g,kind,actor)=>db.prepare('INSERT INTO fw_game_events(game_id,chat_id,kind,actor_id,detail,created_at) VALUES (?,?,?,?,NULL,?)').run(g.id,g.chat_id,'fleet-'+kind,actor,now());
 function insert(chat,ids,state,status='active'){const id=crypto.randomUUID(),time=now();db.prepare('INSERT INTO fw_games(id,chat_id,kind,status,state,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(id,chat,'fleet',status,JSON.stringify(state),time,time);for(const [i,user]of ids.entries())db.prepare('INSERT INTO fw_game_players(game_id,user_id,accepted) VALUES (?,?,?)').run(id,user,status==='invited'?(i===0?1:0):1);return id;}
 function create(chat,user,targets){if(chat==='family'||!Array.isArray(targets)||targets.length!==1||targets[0]===user)throw new Error('Choose one opponent');const ids=[user,...targets],c=db.prepare('SELECT ended_at FROM chats WHERE id=?').get(chat);if(!c||c.ended_at||ids.some(id=>!canAccessChat(chat,id)))throw new Error('Use an active chat with that player');return tx(()=>{if(db.prepare("SELECT id FROM fw_games WHERE chat_id=? AND kind='fleet' AND status IN ('invited','active')").get(chat))throw new Error('Fleet Duel is already open here');const id=insert(chat,ids,initial(ids),'invited');record({id,chat_id:chat},'invite',user);return {id};});}
 function act(id,user,body){requirePlayer(id,user);if(!body||typeof body.actionId!=='string'||! /^[a-f0-9-]{36}$/i.test(body.actionId)||!Number.isSafeInteger(body.revision)||body.revision<0)throw new Error('Action ID and revision are required');const allowed={join:[],fleet:['fleet'],ready:['fleet'],fire:['cell'],resign:[],rematch:[]};if(!Object.hasOwn(allowed,body.action)||Object.keys(body).some(k=>!['actionId','revision','action',...allowed[body.action]].includes(k)))throw new Error('Invalid Fleet Duel action');const canonical={action:body.action,revision:body.revision};for(const key of allowed[body.action])canonical[key]=body[key];const digest=crypto.createHash('sha256').update(JSON.stringify(canonical)).digest('hex');return tx(()=>{const g=requirePlayer(id,user),ps=players(id),ids=ps.map(p=>p.user_id),saved=db.prepare('SELECT digest,response FROM fw_fleet_actions WHERE game_id=? AND actor_id=? AND action_id=?').get(id,user,body.actionId);if(saved){if(saved.digest!==digest)throw new Error('Action ID was already used for a different request');return JSON.parse(saved.response);}const state=JSON.parse(g.state);if(state.revision!==body.revision)throw new Error('Board changed; review the current state');if(g.status==='closed')throw new Error('Game has ended');let next;
 if(body.action==='join'){if(g.status!=='invited'||ps.find(p=>p.user_id===user).accepted)throw new Error('Invitation is no longer open');db.prepare('UPDATE fw_game_players SET accepted=1 WHERE game_id=? AND user_id=?').run(id,user);next={...state,revision:state.revision+1};}
 else {if(g.status==='invited')throw new Error('Wait for your opponent to join');next=play(state,ids,user,body);}
 if(body.action==='rematch'&&next.rematch.length===2&&!next.rematchId){if(db.prepare("SELECT id FROM fw_games WHERE chat_id=? AND kind='fleet' AND status IN ('invited','active') AND id!=?").get(g.chat_id,id))throw new Error('Another Fleet Duel is already open in this chat');next.rematchId=insert(g.chat_id,ids,initial(ids,ids.find(p=>p!==state.starter)));record({id:next.rematchId,chat_id:g.chat_id},'start',user);}
 const status=next.phase==='finished'?'finished':'active';db.prepare('UPDATE fw_games SET state=?,status=?,updated_at=? WHERE id=?').run(JSON.stringify(next),status,now(),id);record(g,body.action==='join'?'accept':next.ending==='victory'&&state.phase!=='finished'?'win':body.action,user);const response={id,revision:next.revision,state:fleetView(next,user,ids),...(next.rematchId?{rematchId:next.rematchId}:{})};db.prepare('INSERT INTO fw_fleet_actions VALUES (?,?,?,?,?)').run(id,user,body.actionId,digest,JSON.stringify(response));return response;});}
 function endForChat(chat,actor){const rows=db.prepare("SELECT * FROM fw_games WHERE chat_id=? AND kind='fleet' AND status IN ('active','invited')").all(chat);if(rows.length)tx(()=>{for(const g of rows){db.prepare("UPDATE fw_games SET status='closed',updated_at=? WHERE id=?").run(now(),g.id);record(g,'close',actor);}});}
 return {create,act,endForChat,view:fleetView};
}
module.exports={initial,play,fleetView,createFleetStore};
