const crypto=require('node:crypto');
const UUID=/^[a-f0-9-]{36}$/i;
const tokenFor=code=>crypto.createHash('sha256').update('FamilyWire-access:'+code).digest('hex');
function createInvitations(db,{secret,codes,ownerUserId='',now=Date.now,onChange=()=>{},onDeleteMember=()=>{}}){
 const key=crypto.createHash('sha256').update('FamilyWire-invitations:'+secret).digest();
 const encrypt=code=>{const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),data=Buffer.concat([cipher.update(code,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),data]).toString('base64');};
 const decrypt=value=>{const b=Buffer.from(value,'base64'),cipher=crypto.createDecipheriv('aes-256-gcm',key,b.subarray(0,12));cipher.setAuthTag(b.subarray(12,28));return Buffer.concat([cipher.update(b.subarray(28)),cipher.final()]).toString('utf8');};
 db.exec(`CREATE TABLE IF NOT EXISTS fw_invitations(token TEXT PRIMARY KEY,code TEXT NOT NULL,assigned_label TEXT NOT NULL DEFAULT '',revoked INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,source TEXT NOT NULL DEFAULT 'configured');
 CREATE TABLE IF NOT EXISTS fw_accounts(user_id TEXT PRIMARY KEY,name TEXT NOT NULL,name_managed INTEGER NOT NULL DEFAULT 0,admin INTEGER NOT NULL DEFAULT 0,owner INTEGER NOT NULL DEFAULT 0,deleted INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS fw_admin_audit(id INTEGER PRIMARY KEY,actor_id TEXT NOT NULL,action TEXT NOT NULL,target_id TEXT,created_at INTEGER NOT NULL);`);
 // Existing claims are authoritative, including legacy code reassignment.
 for(const code of codes){const token=tokenFor(code),h=token.slice(0,32),id=`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;db.prepare('INSERT OR IGNORE INTO invite_claims(token,user_id) VALUES (?,?)').run(token,id);db.prepare('INSERT OR IGNORE INTO fw_invitations(token,code,created_at) VALUES (?,?,?)').run(token,encrypt(code),now());}
 for(const c of db.prepare('SELECT user_id FROM invite_claims').all()){const p=db.prepare('SELECT name FROM people WHERE user_id=?').get(c.user_id);db.prepare('INSERT OR IGNORE INTO fw_accounts(user_id,name) VALUES (?,?)').run(c.user_id,p?.name||'');}
 if(ownerUserId){if(!UUID.test(ownerUserId)||!db.prepare('SELECT user_id FROM invite_claims WHERE user_id=?').get(ownerUserId))throw new Error('Owner bootstrap must identify an existing invitation claim');const owner=db.prepare('SELECT user_id FROM fw_accounts WHERE owner=1 AND deleted=0').get();if(owner&&owner.user_id!==ownerUserId)throw new Error('Existing owner differs from configured owner');db.prepare('UPDATE fw_accounts SET owner=1,admin=1 WHERE user_id=? AND deleted=0').run(ownerUserId);}
 const configured=new Set(codes.map(tokenFor));
 const enabled=row=>row.source==='generated'||configured.has(row.token);
 let depth=0;const tx=work=>{if(depth)return work();db.exec('BEGIN IMMEDIATE');depth++;try{const value=work();db.exec('COMMIT');onChange();return value;}catch(e){db.exec('ROLLBACK');throw e;}finally{depth--;}};
 const audit=(actor,action,target)=>db.prepare('INSERT INTO fw_admin_audit(actor_id,action,target_id,created_at) VALUES (?,?,?,?)').run(actor,action,target||null,now());
 db.exec('CREATE TABLE IF NOT EXISTS fw_admin_receipts(actor_id TEXT NOT NULL,action_id TEXT NOT NULL,request TEXT NOT NULL,result TEXT NOT NULL,PRIMARY KEY(actor_id,action_id))');
 function perform(actor,action,body,work){requireAdmin(actor);if(!UUID.test(body.actionId||''))throw new Error('Action identity required');const request=JSON.stringify([action,body]);return tx(()=>{const prior=db.prepare('SELECT request,result FROM fw_admin_receipts WHERE actor_id=? AND action_id=?').get(actor,body.actionId);if(prior){if(prior.request!==request)throw new Error('Action identity already used for another request');return JSON.parse(decrypt(prior.result));}const result=work();db.prepare('INSERT INTO fw_admin_receipts VALUES (?,?,?,?)').run(actor,body.actionId,request,encrypt(JSON.stringify(result)));return result;});}
 const account=id=>db.prepare('SELECT * FROM fw_accounts WHERE user_id=? AND deleted=0').get(id);
 function requireAdmin(id,owner=false){const a=account(id);if(!a?.admin||(owner&&!a.owner)){const e=new Error(owner?'Owner required':'Administrator required');e.status=403;throw e;}return a;}
 function resolve(token){const row=db.prepare('SELECT i.*,c.user_id,c.device_id FROM fw_invitations i JOIN invite_claims c USING(token) WHERE i.token=? AND i.revoked=0').get(token);return row&&enabled(row)&&account(row.user_id)?row:null;}
 function allowed(){return new Map(db.prepare('SELECT i.token,i.source,c.user_id FROM fw_invitations i JOIN invite_claims c USING(token) JOIN fw_accounts a ON a.user_id=c.user_id WHERE i.revoked=0 AND a.deleted=0').all().filter(enabled).map(r=>[r.token,r.user_id]));}
 function name(id,presented){const a=account(id);if(!a)throw new Error('Account unavailable');if(!a.name_managed&&a.name!==presented){db.prepare('UPDATE fw_accounts SET name=? WHERE user_id=?').run(presented,id);return presented;}return a.name;}
 function rename(actor,id,value){if(actor!==id)requireAdmin(actor);if(typeof value!=='string'||!value.trim()||value.trim().length>32||/[\u0000-\u001f\u007f]/.test(value)||value.trim().toLowerCase()==='family')throw new Error('Use a name of 1–32 characters');if(!account(id))throw new Error('Member unavailable');return tx(()=>{db.prepare('UPDATE fw_accounts SET name=?,name_managed=1 WHERE user_id=?').run(value.trim(),id);db.prepare('UPDATE people SET name=? WHERE user_id=?').run(value.trim(),id);audit(actor,'rename',id);return {userId:id,name:value.trim()};});}
 function list(actor){requireAdmin(actor);return {members:db.prepare('SELECT user_id AS userId,name,admin,owner FROM fw_accounts WHERE deleted=0 AND name!=\'\' ORDER BY name COLLATE NOCASE').all(),invitations:db.prepare('SELECT i.token,i.source,i.code,i.assigned_label,i.revoked,c.user_id,c.device_id,a.name,a.admin,a.owner,a.deleted FROM fw_invitations i JOIN invite_claims c USING(token) LEFT JOIN fw_accounts a ON a.user_id=c.user_id ORDER BY i.created_at,i.rowid').all().map(r=>({id:r.token,userId:r.user_id,assignedTo:r.assigned_label,name:r.deleted?'Deleted member':r.name||'',status:r.revoked||!enabled(r)?'revoked':r.device_id?'claimed':'available',admin:!!r.admin,owner:!!r.owner,code:r.revoked||!enabled(r)?null:r.device_id?null:decrypt(r.code),masked:r.device_id?'Claimed code · reveal deliberately':null}))};}
 function code(actor,token){requireAdmin(actor);const r=resolve(token);if(!r)throw new Error('Invitation unavailable');return {code:decrypt(r.code)};}
 function generate(actor,label=''){requireAdmin(actor);if(typeof label!=='string'||label.length>64)throw new Error('Assigned-to label must be at most 64 characters');const recent=db.prepare("SELECT COUNT(*) AS n FROM fw_admin_audit WHERE actor_id=? AND action='generate' AND created_at>?").get(actor,now()-60000).n;if(recent>=10){const e=new Error('Wait a minute before generating more invitations');e.status=429;throw e;}return tx(()=>{const value=crypto.randomBytes(24).toString('base64url'),token=tokenFor(value),id=crypto.randomUUID();db.prepare('INSERT INTO invite_claims(token,user_id) VALUES (?,?)').run(token,id);db.prepare('INSERT INTO fw_accounts(user_id,name) VALUES (?,?)').run(id,'');db.prepare('INSERT INTO fw_invitations(token,code,assigned_label,created_at,source) VALUES (?,?,?,?,?)').run(token,encrypt(value),label.trim(),now(),'generated');audit(actor,'generate',id);return {id:token,userId:id,code:value};});}
 function role(actor,id,enabled){requireAdmin(actor,true);if(typeof enabled!=='boolean'||!account(id))throw new Error('Invalid member');const target=account(id);if(target.owner&&!enabled)throw new Error('The owner must remain an administrator');return tx(()=>{db.prepare('UPDATE fw_accounts SET admin=? WHERE user_id=?').run(enabled?1:0,id);audit(actor,enabled?'grant-admin':'revoke-admin',id);return {userId:id};});}
 function revoke(actor,token){requireAdmin(actor);const row=resolve(token);if(!row)throw new Error('Invitation unavailable');if(row.device_id)throw new Error('Claimed invitations require explicit member deletion');return tx(()=>{db.prepare('UPDATE fw_invitations SET revoked=1 WHERE token=?').run(token);audit(actor,'revoke',row.user_id);return {id:token};});}
 function remove(actor,id,{confirmUserId,releaseInvitation=false}={}){requireAdmin(actor);const target=account(id);if(!target||confirmUserId!==id||typeof releaseInvitation!=='boolean')throw new Error('Confirm the exact member identity');if(id===actor||target.owner)throw new Error('The owner and your own account cannot be deleted');if(target.admin&&db.prepare('SELECT COUNT(*) AS n FROM fw_accounts WHERE admin=1 AND deleted=0').get().n<=1)throw new Error('The last administrator cannot be deleted');return tx(()=>{onDeleteMember(id,actor);if(db.prepare("SELECT name FROM sqlite_master WHERE name='chats'").get()){for(const chat of db.prepare('SELECT id FROM chats WHERE owner_id=?').all(id)){const next=db.prepare('SELECT user_id FROM chat_members WHERE chat_id=? AND user_id!=? ORDER BY rowid LIMIT 1').get(chat.id,id);if(next)db.prepare('UPDATE chats SET owner_id=? WHERE id=?').run(next.user_id,chat.id);else db.prepare('UPDATE chats SET ended_at=? WHERE id=?').run(now(),chat.id);}}db.prepare("UPDATE fw_accounts SET deleted=1,admin=0,name='' WHERE user_id=?").run(id);db.prepare("UPDATE fw_invitations SET revoked=1,code='' WHERE token IN (SELECT token FROM invite_claims WHERE user_id=?)").run(id);db.prepare('DELETE FROM people WHERE user_id=?').run(id);for(const table of ['chat_members','chat_reads','fw_learning','chip_accounts','chip_ledger'])if(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table))db.prepare('DELETE FROM '+table+' WHERE user_id=?').run(id);if(db.prepare("SELECT name FROM sqlite_master WHERE name='fw_game_players'").get())db.prepare("UPDATE fw_games SET status='closed',updated_at=? WHERE id IN (SELECT game_id FROM fw_game_players WHERE user_id=?)").run(now(),id);audit(actor,'delete-member',id);const result={userId:id,deleted:true};if(releaseInvitation)result.replacement=generate(actor,'Replacement invitation');return result;});
 // Release reuses the invitation slot with a fresh secret and identity. The old
 // secret stays permanently revoked, so an old device cannot reclaim access.
 }
 return {resolve,allowed,account,name,rename,list,code,generate,role,revoke,remove,requireAdmin,perform};
}
module.exports={createInvitations,tokenFor};
