'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {TTL,LIMITS,id,validateDescriptor}=require('./shared-whiteboard.cjs');
function fail(status,message){const error=Error(message);error.status=status;throw error;}
function createWhiteboardStore(db,{now=Date.now,chatMembers,canAccess,chatEnded,admission,capacity,filesDir}){
 db.exec('CREATE TABLE IF NOT EXISTS metadata(key TEXT PRIMARY KEY,value TEXT)');
 db.exec(`CREATE TABLE IF NOT EXISTS fw_boards(id TEXT PRIMARY KEY,chat_id TEXT NOT NULL,owner_id TEXT NOT NULL,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,revision INTEGER NOT NULL DEFAULT 0);
 CREATE INDEX IF NOT EXISTS fw_boards_chat ON fw_boards(chat_id,expires_at);
 CREATE TABLE IF NOT EXISTS fw_board_members(board_id TEXT NOT NULL,user_id TEXT NOT NULL,admission INTEGER NOT NULL,left_at INTEGER,PRIMARY KEY(board_id,user_id));
 CREATE TABLE IF NOT EXISTS fw_board_ops(id TEXT PRIMARY KEY,board_id TEXT NOT NULL,revision INTEGER NOT NULL,actor_id TEXT NOT NULL,kind TEXT NOT NULL,target TEXT NOT NULL,touched TEXT NOT NULL,asset_id TEXT NOT NULL,expected INTEGER NOT NULL,frame TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(board_id,revision));
 CREATE TABLE IF NOT EXISTS fw_board_assets(id TEXT PRIMARY KEY,board_id TEXT NOT NULL,uploader TEXT NOT NULL,size INTEGER NOT NULL,hash TEXT NOT NULL,created_at INTEGER NOT NULL);`);
 function eligible(board,user){const grant=db.prepare('SELECT * FROM fw_board_members WHERE board_id=? AND user_id=?').get(board.id,user);return !!grant&&grant.left_at===null&&canAccess(board.chat_id,user)&&admission(board.chat_id,user)===grant.admission;}
 function access(boardId,chat,user){id(boardId);const board=db.prepare('SELECT * FROM fw_boards WHERE id=? AND chat_id=?').get(boardId,chat);if(!board||board.expires_at<=now())fail(410,'This whiteboard has expired');if(!eligible(board,user))fail(403,'Whiteboard access denied');if(!eligible(board,board.owner_id)){const owner=db.prepare('SELECT user_id FROM fw_board_members WHERE board_id=? ORDER BY rowid').all(board.id).find(row=>eligible(board,row.user_id));if(owner){db.prepare('UPDATE fw_boards SET owner_id=? WHERE id=?').run(owner.user_id,board.id);board.owner_id=owner.user_id;}}return board;}
 function recovery(boardId){const row=db.prepare('SELECT value FROM metadata WHERE key=?').get('whiteboard-recovered:'+boardId);return row?JSON.parse(row.value):null;}
 function writable(board){if(chatEnded(board.chat_id))fail(409,'Chat has ended');if(recovery(board.id))fail(409,'This board was preserved for recovery. Reopen the current whiteboard');}
 function revoke(chat,user){db.prepare('UPDATE fw_board_members SET left_at=? WHERE user_id=? AND board_id IN (SELECT id FROM fw_boards WHERE chat_id=?)').run(now(),user,chat);}
 function revokeMember(user){db.prepare('UPDATE fw_board_members SET left_at=? WHERE user_id=?').run(now(),user);}
 function recover(boardId,chat,user,body){
  const board=access(boardId,chat,user);if(board.owner_id!==user||chatEnded(chat))fail(403,'Active board owner required');id(body.replacementId);
  const prior=recovery(board.id);if(prior){if(prior.replacementId!==body.replacementId||prior.revision!==body.baseRevision)fail(409,'This board already has a replacement');return {board:view(access(prior.replacementId,chat,user),user),preservedBoardId:board.id,preservedUntil:board.expires_at};}
  if(body.replacementId===board.id||db.prepare('SELECT id FROM fw_boards WHERE id=?').get(body.replacementId))fail(409,'Replacement board ID already used');
  if(!Number.isSafeInteger(body.baseRevision)||body.baseRevision!==board.revision)fail(409,'The board changed. Recheck recovery before continuing');
  if(db.prepare('SELECT COUNT(*) AS n FROM fw_boards WHERE chat_id=? AND expires_at>?').get(chat,now()).n>=5)fail(422,'Recovery board limit reached. Preserved boards remain available until their expiry');
  capacity(16384);const next={id:body.replacementId,chat_id:chat,owner_id:user,created_at:now(),expires_at:now()+TTL,revision:0};
  const participants=db.prepare('SELECT user_id FROM fw_board_members WHERE board_id=?').all(board.id).map(row=>row.user_id).filter(member=>eligible(board,member));
  db.exec('BEGIN');try{
   db.prepare('INSERT INTO fw_boards(id,chat_id,owner_id,created_at,expires_at) VALUES (?,?,?,?,?)').run(next.id,chat,user,next.created_at,next.expires_at);
   for(const member of participants)db.prepare('INSERT INTO fw_board_members(board_id,user_id,admission) VALUES (?,?,?)').run(next.id,member,admission(chat,member));
   db.prepare('INSERT INTO metadata(key,value) VALUES (?,?)').run('whiteboard-recovered:'+board.id,JSON.stringify({replacementId:next.id,revision:board.revision,createdAt:now()}));
   db.exec('COMMIT');
  }catch(error){db.exec('ROLLBACK');throw error;}
  return {board:view(next,user),preservedBoardId:board.id,preservedUntil:board.expires_at};
 }
 function view(board,user){return {id:board.id,chatId:board.chat_id,ownerId:board.owner_id,createdAt:board.created_at,expiresAt:board.expires_at,revision:board.revision,readOnly:!!chatEnded(board.chat_id)||!!recovery(board.id),canClear:board.owner_id===user&&!chatEnded(board.chat_id)&&!recovery(board.id),recoveredInto:recovery(board.id)?.replacementId||null,participants:db.prepare('SELECT user_id FROM fw_board_members WHERE board_id=? ORDER BY rowid').all(board.id).map(row=>row.user_id).filter(member=>eligible(board,member))};}
 function open(chat,user){if(!canAccess(chat,user))fail(403,'Chat access denied');const current=db.prepare('SELECT * FROM fw_boards WHERE chat_id=? AND expires_at>? ORDER BY created_at DESC,rowid DESC').all(chat,now()).find(board=>!recovery(board.id));if(current)return view(access(current.id,chat,user),user);if(chatEnded(chat))fail(409,'Chat has ended');capacity(16384);const board={id:crypto.randomUUID(),chat_id:chat,owner_id:user,created_at:now(),expires_at:now()+TTL,revision:0};db.exec('BEGIN');try{db.prepare('INSERT INTO fw_boards(id,chat_id,owner_id,created_at,expires_at) VALUES (?,?,?,?,?)').run(board.id,chat,user,board.created_at,board.expires_at);for(const member of new Set([user,...chatMembers(chat)]))if(canAccess(chat,member))db.prepare('INSERT INTO fw_board_members(board_id,user_id,admission) VALUES (?,?,?)').run(board.id,member,admission(chat,member));db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}return view(board,user);}
 function list(boardId,chat,user,after=0){const board=access(boardId,chat,user);if(!Number.isSafeInteger(after)||after<0||after>board.revision)fail(400,'Invalid whiteboard cursor');const rows=db.prepare('SELECT id,revision AS seq,actor_id AS actorId,kind AS type,target,asset_id AS asset,expected,frame,created_at AS time FROM fw_board_ops WHERE board_id=? AND revision>? ORDER BY revision LIMIT 100').all(board.id,after);return {board:view(board,user),operations:rows};}
 function append(boardId,chat,user,body){const board=access(boardId,chat,user);writable(board);try{validateDescriptor(body.operation);}catch(error){fail(400,error.message);}const op=body.operation;
  if(typeof body.frame!=='string'||body.frame.length>Math.ceil(LIMITS.frame/3)*4||!/^[A-Za-z0-9+/]+={0,2}$/.test(body.frame)||Buffer.from(body.frame,'base64').length<28||Buffer.from(body.frame,'base64').toString('base64')!==body.frame)fail(400,'Invalid encrypted board operation');
  const previous=db.prepare('SELECT * FROM fw_board_ops WHERE id=?').get(op.id);if(previous){if(previous.board_id!==board.id||previous.actor_id!==user||previous.frame!==body.frame||previous.kind!==op.type||previous.target!==op.target||previous.asset_id!==op.asset||previous.expected!==op.expected)fail(409,'Board operation ID was reused');return {ok:true,revision:previous.revision,duplicate:true};}
  if(!Number.isSafeInteger(body.baseRevision)||body.baseRevision!==board.revision)fail(409,'The board changed. Review the latest version');if(board.revision>=LIMITS.operations)fail(422,'Whiteboard change limit reached');
  let touched=op.target;if(op.type==='clear'){if(board.owner_id!==user)fail(403,'Only the board owner can clear it');touched='*';}
  if(op.type==='add'&&op.asset&&!db.prepare('SELECT id FROM fw_board_assets WHERE id=? AND board_id=?').get(op.asset,board.id))fail(400,'Board image upload missing');
  if(['transform','remove','order'].includes(op.type)){const last=db.prepare('SELECT revision FROM fw_board_ops WHERE board_id=? AND (touched=? OR touched=?) ORDER BY revision DESC LIMIT 1').get(board.id,op.target,'*');if(!last||last.revision!==op.expected)fail(409,'This object changed. Review the latest board');}
  if(op.type==='undo'){const original=db.prepare('SELECT * FROM fw_board_ops WHERE id=? AND board_id=?').get(op.target,board.id);if(!original||original.actor_id!==user||original.kind==='undo'||db.prepare("SELECT id FROM fw_board_ops WHERE board_id=? AND kind='undo' AND target=?").get(board.id,op.target))fail(403,'Only your own available changes can be undone');if(original.kind==='clear'?board.revision!==original.revision:!!db.prepare('SELECT id FROM fw_board_ops WHERE board_id=? AND revision>? AND (touched=? OR touched=?)').get(board.id,original.revision,original.touched,'*'))fail(409,'Someone changed the board after that action');touched=original.touched;}
  const used=db.prepare('SELECT COALESCE(SUM(length(frame)),0) AS bytes FROM fw_board_ops WHERE board_id=?').get(board.id).bytes;if(used+body.frame.length>8*1024*1024)fail(422,'Whiteboard storage limit reached');capacity(body.frame.length*3+8192);const revision=board.revision+1;
  db.exec('BEGIN');try{db.prepare('INSERT INTO fw_board_ops(id,board_id,revision,actor_id,kind,target,touched,asset_id,expected,frame,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(op.id,board.id,revision,user,op.type,op.target,touched,op.asset,op.expected,body.frame,now());db.prepare('UPDATE fw_boards SET revision=? WHERE id=?').run(revision,board.id);db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}return {ok:true,revision};
 }
 function invite(boardId,chat,user,ids){const board=access(boardId,chat,user);if(board.owner_id!==user||chatEnded(chat)||recovery(board.id))fail(403,'Active board owner required');if(!Array.isArray(ids)||ids.length>20)fail(400,'Invalid board participants');for(const member of ids)if(!canAccess(chat,id(member)))fail(403,'Participant must belong to this chat');for(const member of ids)db.prepare('INSERT INTO fw_board_members(board_id,user_id,admission,left_at) VALUES (?,?,?,NULL) ON CONFLICT(board_id,user_id) DO UPDATE SET admission=excluded.admission,left_at=NULL').run(board.id,member,admission(chat,member));return view(board,user);}
 function leave(boardId,chat,user,transferTo){const board=access(boardId,chat,user);if(board.owner_id===user){if(!transferTo||transferTo===user||!eligible(board,id(transferTo)))fail(409,'Transfer ownership to another participant before leaving');db.prepare('UPDATE fw_boards SET owner_id=? WHERE id=?').run(transferTo,board.id);}db.prepare('UPDATE fw_board_members SET left_at=? WHERE board_id=? AND user_id=?').run(now(),board.id,user);return {ok:true};}
 function putAsset(boardId,chat,user,assetId,bytes){const board=access(boardId,chat,user);id(assetId);writable(board);if(bytes.length<28||bytes.length>LIMITS.imageBytes+28)fail(413,'Board image too large');const digest=crypto.createHash('sha256').update(bytes).digest('hex'),old=db.prepare('SELECT * FROM fw_board_assets WHERE id=?').get(assetId);if(old){if(old.board_id!==board.id||old.uploader!==user||old.hash!==digest)fail(409,'Board image ID was reused');return {ok:true};}
  const totals=db.prepare('SELECT COUNT(*) AS n,COALESCE(SUM(size),0) AS bytes FROM fw_board_assets WHERE board_id=?').get(board.id);if(totals.n>=LIMITS.assets||totals.bytes+bytes.length>12*1024*1024)fail(422,'Whiteboard image storage limit reached');capacity(bytes.length+8192);const file=path.join(filesDir,'board-'+assetId),temp=file+'.'+crypto.randomUUID()+'.tmp';try{fs.writeFileSync(temp,bytes,{flag:'wx',flush:true});fs.renameSync(temp,file);db.prepare('INSERT INTO fw_board_assets(id,board_id,uploader,size,hash,created_at) VALUES (?,?,?,?,?,?)').run(assetId,board.id,user,bytes.length,digest,now());}catch(error){fs.rmSync(temp,{force:true});if(!db.prepare('SELECT id FROM fw_board_assets WHERE id=?').get(assetId))fs.rmSync(file,{force:true});throw error;}return {ok:true};
 }
 function getAsset(boardId,chat,user,assetId){const board=access(boardId,chat,user);id(assetId);const record=db.prepare('SELECT * FROM fw_board_assets WHERE id=? AND board_id=?').get(assetId,board.id);if(!record)fail(404,'Board image unavailable');const file=path.join(filesDir,'board-'+assetId);if(!fs.existsSync(file)||fs.statSync(file).size!==record.size)fail(404,'Board image unavailable');return file;}
 function prune(){for(const board of db.prepare('SELECT id FROM fw_boards WHERE expires_at<=?').all(now())){for(const asset of db.prepare('SELECT id FROM fw_board_assets WHERE board_id=?').all(board.id))fs.rmSync(path.join(filesDir,'board-'+asset.id),{force:true});for(const table of ['fw_board_ops','fw_board_assets','fw_board_members'])db.prepare('DELETE FROM '+table+' WHERE board_id=?').run(board.id);db.prepare('DELETE FROM fw_boards WHERE id=?').run(board.id);db.prepare('DELETE FROM metadata WHERE key=?').run('whiteboard-recovered:'+board.id);}}
 return {open,list,append,invite,leave,recover,revoke,revokeMember,putAsset,getAsset,prune};
}
module.exports={createWhiteboardStore};
