(function(){
'use strict';
const SCENE_URL='/assets/worlds/whisperwind_village.json';
const STATE_API='/api/estate/neighborhoods/whisperwind_01';
const CLAIM_API='/api/estate/neighborhoods/whisperwind_01/claim';
const state={canvas:null,ctx:null,dpr:1,scene:null,assets:{},running:false,last:0,cam:{x:0,y:0},player:{x:0,y:0,face:'down',moving:false,animT:0},keys:{},username:'Wanderer',near:null,dialog:null,remote:new Map(),ws:null,worldId:null,plots:{},onClose:null,minimap:null,minimapCtx:null,grassSeed:[]};
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function dist(a,b,c,d){return Math.hypot(a-c,b-d);}
function safeName(n){return String(n||'Wanderer').slice(0,18);}
function assetUrl(name){return !name?'':name.startsWith('/')?name:'/assets/worldkit/'+name;}
function loadImage(url){return new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>{console.warn('[RPG] asset failed',url);resolve(null);};img.src=url;});}
function sceneAssets(scene){const urls=new Set();function add(a){if(a)urls.add(assetUrl(a));} [...(scene.objects||[]),...(scene.decorations||[])].forEach(o=>add(o.asset));(scene.avatar&&scene.avatar.layers||[]).forEach(l=>add(l.asset)); return [...urls];}
async function preload(scene){await Promise.all(sceneAssets(scene).map(async u=>{state.assets[u]=await loadImage(u);}));}
function mount(){
  const root=document.createElement('div');root.className='gfRpgRoot';
  root.innerHTML=`
    <canvas id="gfRpgCanvas"></canvas>
    <div class="gfAreaTitle"><b>Whisperwind Village</b><span>JRPG town rebuild • objects, water, empty homes</span></div>
    <button class="gfLeave" id="gfLeave">Leave</button>
    <canvas class="gfMinimap" id="gfMinimap" width="190" height="150"></canvas>
    <div class="gfPrompt hidden" id="gfPrompt"></div>
    <div class="gfQuest" id="gfQuest"><button title="Close" id="gfQuestClose">×</button><b>Whisperwind 2.0</b><p>Walk with WASD / arrows. Press <b>E</b> near NPCs, cottages, the board, Echo Hall, or the dock.</p></div>
    <div class="gfDialog hidden" id="gfDialog"><button id="gfDialogClose">×</button><div id="gfDialogText"></div></div>
    <div class="gfChat"><span>Multiplayer presence is active in this scene.</span></div>
    <div class="gfHotbar"><button>Bag</button><button>Build</button><button>Map</button></div>`;
  document.body.appendChild(root);state.canvas=root.querySelector('#gfRpgCanvas');state.ctx=state.canvas.getContext('2d');state.minimap=root.querySelector('#gfMinimap');state.minimapCtx=state.minimap.getContext('2d');
  root.querySelector('#gfLeave').onclick=()=>stop();root.querySelector('#gfQuestClose').onclick=()=>root.querySelector('#gfQuest').classList.add('hidden');root.querySelector('#gfDialogClose').onclick=closeDialog;
  window.addEventListener('resize',resize);window.addEventListener('keydown',onKey,true);window.addEventListener('keyup',onKey,true);resize();
}
function resize(){const c=state.canvas;if(!c)return;state.dpr=Math.max(1,Math.min(2,window.devicePixelRatio||1));const w=c.clientWidth,h=c.clientHeight;c.width=Math.floor(w*state.dpr);c.height=Math.floor(h*state.dpr);state.ctx.setTransform(state.dpr,0,0,state.dpr,0,0);}
async function start(opts){opts=opts||{};state.username=safeName(opts.username||localStorage.getItem('gf_user')||'Wanderer');state.onClose=opts.onClose||null;if(!state.canvas)mount();const scene=await fetch(SCENE_URL+'?v='+Date.now(),{cache:'no-store'}).then(r=>r.json());state.scene=scene;state.assets={};makeGrassSeed(scene);await preload(scene);await fetchEstateState();state.player={x:scene.spawn.x,y:scene.spawn.y,face:scene.spawn.face||'down',moving:false,animT:0};state.cam.x=clamp(state.player.x-state.canvas.clientWidth/2,0,scene.size.w-state.canvas.clientWidth);state.cam.y=clamp(state.player.y-state.canvas.clientHeight/2,0,scene.size.h-state.canvas.clientHeight);connectWS();state.running=true;state.last=performance.now();requestAnimationFrame(loop);}
function stop(){state.running=false;try{if(state.ws)state.ws.send(JSON.stringify({type:'worldLeave'}));}catch(e){} if(state.onClose)state.onClose();}
function makeGrassSeed(scene){state.grassSeed=[];let seed=1337;function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}for(let i=0;i<950;i++){state.grassSeed.push({x:rnd()*scene.size.w,y:rnd()*scene.size.h,t:Math.floor(rnd()*4),s:.55+rnd()*1.4,a:.25+rnd()*.55});}}
async function fetchEstateState(){try{const j=await fetch(STATE_API,{cache:'no-store'}).then(r=>r.json());state.plots={};if(j&&j.ok&&j.neighborhood){(j.neighborhood.plots||[]).forEach(p=>state.plots[p.id]=p);}}catch(e){state.plots={};}}
async function claimPlot(plotId){try{const j=await fetch(CLAIM_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:state.username,plotId})}).then(r=>r.json());if(j.ok){await fetchEstateState();openDialog('Home claimed for testing! Later this door will open your customizable interior.');}else openDialog(j.error||'That home could not be claimed.');}catch(e){openDialog('The home service is unavailable, but the cottage interaction is wired.');}}
function onKey(e){const down=e.type==='keydown';const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(k)){state.keys[k]=down;e.preventDefault();}if(down&&(k==='e'||e.key===' ')){if(state.dialog)closeDialog();else interact();e.preventDefault();}if(down&&k==='escape')closeDialog();}
function interact(){const n=state.near;if(!n)return;const t=n.target;if(t.kind==='npc'){openDialog((t.name?t.name+':\n':'')+(t.dialogue||[]).join('\n\n'));return;}if(t.kind==='home'){if(t.owner){openDialog((t.owner===state.username?'Your':'A')+' cottage. House interiors and visitor permissions are next.');}else claimPlot(t.plotId);return;}openDialog(t.message||t.label||'Nothing happens yet.');}
function openDialog(text){state.dialog=text;document.getElementById('gfDialogText').textContent=text;document.getElementById('gfDialog').classList.remove('hidden');}
function closeDialog(){state.dialog=null;const d=document.getElementById('gfDialog');if(d)d.classList.add('hidden');}
function update(dt){const p=state.player;let dx=0,dy=0;if(state.keys.w||state.keys.arrowup)dy-=1;if(state.keys.s||state.keys.arrowdown)dy+=1;if(state.keys.a||state.keys.arrowleft)dx-=1;if(state.keys.d||state.keys.arrowright)dx+=1;if(dx||dy){const l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;p.face=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');}
  const sp=(state.scene.player&&state.scene.player.speed)||220;const nx=p.x+dx*sp*dt,ny=p.y+dy*sp*dt;p.moving=!!(dx||dy);p.animT=(p.animT||0)+dt;if(p.moving){let moved=false;if(canStand(nx,ny)){p.x=nx;p.y=ny;moved=true;}else{if(canStand(nx,p.y)){p.x=nx;moved=true;}if(canStand(p.x,ny)){p.y=ny;moved=true;}}if(moved)sendMove();}
  const vw=state.canvas.clientWidth,vh=state.canvas.clientHeight,sw=state.scene.size.w,sh=state.scene.size.h;const tx=clamp(p.x-vw/2,0,Math.max(0,sw-vw)),ty=clamp(p.y-vh/2,0,Math.max(0,sh-vh));const s=(state.scene.camera&&state.scene.camera.smoothing)||.14;state.cam.x+=(tx-state.cam.x)*s;state.cam.y+=(ty-state.cam.y)*s;findNear();}
function canStand(x,y){const sc=state.scene;if(x<35||y<35||x>sc.size.w-35||y>sc.size.h-35)return false;for(const w of sc.waterAreas||[]){if(pointInPoly([x,y],w.points))return false;}for(const o of [...(sc.objects||[]),...(sc.decorations||[])]){if(!o.solid)continue;const s=o.solid;if(x>o.x+s.x&&x<o.x+s.x+s.w&&y>o.y+s.y&&y<o.y+s.y+s.h)return false;}return true;}
function pointInPoly(p,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const xi=poly[i][0],yi=poly[i][1],xj=poly[j][0],yj=poly[j][1];const inter=((yi>p[1])!=(yj>p[1]))&&(p[0]<(xj-xi)*(p[1]-yi)/(yj-yi)+xi);if(inter)inside=!inside;}return inside;}
function findNear(){const p=state.player;let best=null;function consider(target,x,y,r){const d=dist(p.x,p.y,x,y);if(d<(r||115)&&(!best||d<best.d))best={d,target};}
  for(const n of state.scene.npcs||[])consider({kind:'npc',name:n.name,dialogue:n.dialogue,label:(n.interact&&n.interact.label)||('Talk to '+n.name)},n.x,n.y,(n.interact&&n.interact.radius)||110);
  for(const o of state.scene.objects||[]){if(!o.interact)continue;consider({kind:o.interact.kind||'inspect',label:o.interact.label,message:o.interact.message},o.x,o.y,o.interact.radius||125);}
  for(const pl of state.scene.plots||[]){const live=state.plots[pl.id]||{};consider({kind:'home',plotId:pl.id,owner:live.owner||null,label:live.owner?('Visit '+safeName(live.owner)+'\'s Cottage'):'Buy Empty Cottage'},pl.houseX||pl.x+pl.w/2,pl.houseY||pl.y+pl.h-50,135);}
  state.near=best;const pr=document.getElementById('gfPrompt');if(best){pr.textContent='[E] '+best.target.label;pr.classList.remove('hidden');}else pr.classList.add('hidden');}
function loop(now){if(!state.running)return;const dt=Math.min(.035,(now-state.last)/1000||.016);state.last=now;update(dt);draw(now);requestAnimationFrame(loop);}
function draw(now){const ctx=state.ctx,c=state.canvas,cam=state.cam,vw=c.clientWidth,vh=c.clientHeight;ctx.clearRect(0,0,vw,vh);ctx.save();ctx.translate(-cam.x,-cam.y);drawGround(ctx);drawWater(ctx,now);drawPaths(ctx);drawPlotsBase(ctx);const ents=[];[...(state.scene.decorations||[]),...(state.scene.objects||[])].forEach(o=>ents.push({y:o.y+(o.depthOffset||0),type:'obj',o}));(state.scene.plots||[]).forEach(p=>ents.push({y:(p.houseY||p.y+p.h-40),type:'home',o:p}));(state.scene.npcs||[]).forEach(n=>ents.push({y:n.y,type:'npc',o:n}));state.remote.forEach(r=>ents.push({y:r.y,type:'remote',o:r}));ents.push({y:state.player.y,type:'player',o:state.player});ents.sort((a,b)=>a.y-b.y);for(const e of ents){if(e.type==='obj')drawAsset(ctx,e.o);else if(e.type==='home')drawHouse(ctx,e.o);else if(e.type==='npc')drawAvatar(ctx,e.o.x,e.o.y,e.o.name||'NPC',true,e.o);else if(e.type==='remote')drawAvatar(ctx,e.o.x,e.o.y,e.o.username||'Player',true,e.o);else drawAvatar(ctx,state.player.x,state.player.y,state.username,false,state.player);}ctx.restore();drawMinimap();}
function drawGround(ctx){const sc=state.scene;const g=ctx.createLinearGradient(0,0,0,sc.size.h);g.addColorStop(0,'#5f9f47');g.addColorStop(.55,'#4d843d');g.addColorStop(1,'#3e7035');ctx.fillStyle=g;ctx.fillRect(0,0,sc.size.w,sc.size.h);for(const s of state.grassSeed){ctx.globalAlpha=s.a;ctx.fillStyle=s.t===0?'#78b957':s.t===1?'#3f7a36':s.t===2?'#8dc767':'#315f31';ctx.fillRect(s.x,s.y,2*s.s,8*s.s);ctx.fillRect(s.x-3*s.s,s.y+4*s.s,8*s.s,2*s.s);}ctx.globalAlpha=1;}
function drawWater(ctx,now){for(const w of state.scene.waterAreas||[]){ctx.save();ctx.beginPath();w.points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();const g=ctx.createLinearGradient(0,0,state.scene.size.w,state.scene.size.h);g.addColorStop(0,'#45b9c8');g.addColorStop(.45,'#1e7fa4');g.addColorStop(1,'#0c4c77');ctx.fillStyle=g;ctx.fill();ctx.clip();ctx.globalAlpha=.25;ctx.strokeStyle='#d7ffff';ctx.lineWidth=2;for(let y=-120;y<state.scene.size.h+120;y+=56){ctx.beginPath();for(let x=-120;x<state.scene.size.w+120;x+=52){const yy=y+Math.sin((x*.018)+(now*.0012))*8+(Math.sin(now*.0007+y*.02)*5);x===-120?ctx.moveTo(x,yy):ctx.lineTo(x,yy);}ctx.stroke();}ctx.globalAlpha=.18;ctx.fillStyle='#ffffff';for(let i=0;i<40;i++){const x=(i*173+now*.018)%state.scene.size.w,y=(i*97+now*.012)%state.scene.size.h;ctx.fillRect(x,y,20,2);}ctx.restore();ctx.strokeStyle='rgba(232,255,241,.55)';ctx.lineWidth=8;ctx.stroke();ctx.strokeStyle='rgba(32,48,29,.35)';ctx.lineWidth=18;ctx.stroke();}}
function drawPaths(ctx){ctx.lineCap='round';ctx.lineJoin='round';for(const p of state.scene.paths||[]){strokePath(ctx,p.points,'#4d3a26',p.width+38);strokePath(ctx,p.points,'#82613d',p.width+24);strokePath(ctx,p.points,'#c59e64',p.width);drawCobble(ctx,p.points,p.width);strokePath(ctx,p.points,'rgba(255,242,196,.18)',5);}}
function strokePath(ctx,pts,color,width){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.stroke();}
function drawCobble(ctx,pts,width){ctx.save();for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1],dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len;const steps=Math.max(4,Math.floor(len/42));for(let j=0;j<steps;j++){const t=(j+.5)/steps,cx=a[0]+dx*t,cy=a[1]+dy*t;for(let k=-3;k<=3;k++){if(Math.abs(k)===3&&j%2)continue;const off=k*(width/7)+(((i+j+k)*13)%13-6);ctx.fillStyle=((i+j+k)%3)?'rgba(255,231,176,.18)':'rgba(74,55,34,.22)';ctx.beginPath();ctx.ellipse(cx+nx*off,cy+ny*off,12,5,Math.atan2(dy,dx),0,Math.PI*2);ctx.fill();}}}ctx.restore();}
function drawPlotsBase(ctx){for(const p of state.scene.plots||[]){ctx.save();ctx.fillStyle='rgba(56,91,42,.22)';roundRect(ctx,p.x,p.y,p.w,p.h,28,true,false);ctx.strokeStyle='rgba(255,244,190,.18)';ctx.lineWidth=3;ctx.setLineDash([12,14]);roundRect(ctx,p.x,p.y,p.w,p.h,28,false,true);ctx.setLineDash([]);ctx.restore();}}
function drawHouse(ctx,p){drawAsset(ctx,{asset:'/assets/worldkit/whisperwind/starter_cottage_gameforge.png',x:p.houseX||p.x+p.w/2,y:p.houseY||p.y+p.h-20,w:430,h:330,solid:null});const live=state.plots[p.id]||{};const owner=live.owner?safeName(live.owner):'Available Home';ctx.save();ctx.font='700 15px Arial';ctx.textAlign='center';ctx.lineWidth=4;ctx.strokeStyle='rgba(0,0,0,.72)';ctx.strokeText(owner,p.houseX||p.x+p.w/2,(p.houseY||p.y+p.h-20)+20);ctx.fillStyle=live.owner?'#ffec82':'#d7fff5';ctx.fillText(owner,p.houseX||p.x+p.w/2,(p.houseY||p.y+p.h-20)+20);ctx.restore();}
function drawAsset(ctx,o){const img=state.assets[assetUrl(o.asset)];if(!img)return;const w=o.w||img.width,h=o.h||img.height;ctx.drawImage(img,o.x-w/2,o.y-h,w,h);}
function drawAvatar(ctx,x,y,name,muted,entity){const cfg=state.scene.avatar||{},scale=(state.scene.player&&state.scene.player.scale)||1.45,fw=cfg.frameW||64,fh=cfg.frameH||64;const map=cfg.rows||{down:0,left:1,right:2,up:3};const face=(entity&&entity.face)||'down',row=map[face]||0;const col=(entity&&entity.moving)?(Math.floor(((entity.animT||performance.now()/1000)*8))%(cfg.walkFrames||4)):0;const dw=fw*scale,dh=fh*scale;ctx.save();ctx.globalAlpha=muted?.95:1;ctx.fillStyle='rgba(0,0,0,.26)';ctx.beginPath();ctx.ellipse(x,y-5,dw*.28,7,0,0,Math.PI*2);ctx.fill();for(const l of cfg.layers||[]){const img=state.assets[assetUrl(l.asset)];if(!img)continue;try{ctx.drawImage(img,col*fw,row*fh,fw,fh,x-dw/2,y-dh,dw,dh);}catch(e){}}
  ctx.font='700 14px Arial';ctx.textAlign='center';ctx.lineWidth=4;ctx.strokeStyle='rgba(0,0,0,.75)';ctx.strokeText(name,x,y-dh-8);ctx.fillStyle=muted?'#eafff4':'#ffed77';ctx.fillText(name,x,y-dh-8);ctx.restore();}
function drawMinimap(){const ctx=state.minimapCtx,mm=state.minimap,sc=state.scene;if(!ctx||!sc)return;const w=mm.width,h=mm.height,sx=w/sc.size.w,sy=h/sc.size.h;ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(9,22,13,.88)';ctx.fillRect(0,0,w,h);ctx.fillStyle='#477a38';ctx.fillRect(5,5,w-10,h-10);ctx.save();ctx.translate(5,5);ctx.scale((w-10)/sc.size.w,(h-10)/sc.size.h);ctx.fillStyle='#247d9e';for(const wa of sc.waterAreas||[]){ctx.beginPath();wa.points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fill();}ctx.strokeStyle='#d2ad70';ctx.lineWidth=70;for(const p of sc.paths||[]){ctx.beginPath();p.points.forEach((pt,i)=>i?ctx.lineTo(pt[0],pt[1]):ctx.moveTo(pt[0],pt[1]));ctx.stroke();}ctx.fillStyle='#66d8ff';for(const o of sc.objects||[])ctx.fillRect(o.x-45,o.y-45,90,90);ctx.fillStyle='#ffeb61';ctx.beginPath();ctx.arc(state.player.x,state.player.y,90,0,Math.PI*2);ctx.fill();ctx.restore();ctx.strokeStyle='rgba(255,238,168,.55)';ctx.lineWidth=2;ctx.strokeRect(1,1,w-2,h-2);}
function roundRect(ctx,x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();if(fill)ctx.fill();if(stroke)ctx.stroke();}
function connectWS(){try{const proto=location.protocol==='https:'?'wss':'ws';const ws=new WebSocket(proto+'://'+location.host);state.ws=ws;ws.onopen=()=>ws.send(JSON.stringify({type:'worldJoin',username:state.username,sceneId:state.scene.id,x:state.player.x,y:state.player.y,face:state.player.face,moving:false,appearance:{avatar:'layered_v1'}}));ws.onmessage=ev=>{let m;try{m=JSON.parse(ev.data);}catch(e){return;}if(m.type==='worldWelcome'){state.worldId=m.id;(m.peers||[]).forEach(p=>state.remote.set(p.id,p));}if(m.type==='worldJoin'||m.type==='worldMove'){const p=m.player;if(p&&p.id!==state.worldId)state.remote.set(p.id,p);}if(m.type==='worldLeave')state.remote.delete(m.id);};ws.onclose=()=>setTimeout(()=>{if(state.running)connectWS();},2000);}catch(e){}}
let lastMove=0;function sendMove(){const now=performance.now();if(!state.ws||state.ws.readyState!==1||now-lastMove<80)return;lastMove=now;state.ws.send(JSON.stringify({type:'worldMove',x:Math.round(state.player.x),y:Math.round(state.player.y),face:state.player.face,moving:state.player.moving,appearance:{avatar:'layered_v1'}}));}
window.RPGSceneEngine={start,stop};
})();
