(function(){
'use strict';
var E={root:null,canvas:null,ctx:null,ui:null,scene:null,assets:{},catalog:{},keys:{},player:{x:900,y:720,vx:0,vy:0,face:'down',moving:false},cam:{x:0,y:0,zoom:1},last:0,raf:0,debug:false,username:'Wanderer',onClose:null,msg:'',msgTimer:0,near:null};
function $(s){return document.querySelector(s)}
function loadJson(url){return fetch(url+'?v='+(Date.now()),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(url);return r.json()})}
function img(src){if(E.assets[src])return Promise.resolve(E.assets[src]);return new Promise(res=>{var im=new Image();im.onload=()=>{E.assets[src]=im;res(im)};im.onerror=()=>res(null);im.src=src})}
function inject(){if($('#wfStyle'))return;var st=document.createElement('style');st.id='wfStyle';st.textContent=`
.wfRoot{position:fixed;inset:0;background:#071019;overflow:hidden;touch-action:none}.wfCanvas{position:absolute;inset:0;width:100%;height:100%;image-rendering:auto}.wfHud{position:absolute;inset:0;pointer-events:none}.wfPanel{position:absolute;background:rgba(6,10,16,.72);border:1px solid rgba(238,201,111,.48);box-shadow:0 14px 40px #0008;border-radius:18px;color:#f6edd0;backdrop-filter:blur(8px)}.wfTop{left:18px;top:18px;padding:14px 18px;min-width:260px}.wfTop h1{font:800 22px Georgia,serif;margin:0 0 4px;color:#ffe9a6;text-shadow:0 3px 12px #000}.wfTop p{margin:0;color:#bcd6c9;font-weight:800;font-size:13px}.wfClose{position:absolute;right:18px;top:18px;pointer-events:auto;border:1px solid #e8c767;background:#151305;color:#ffeda8;border-radius:18px;padding:12px 18px;font-weight:900}.wfHint{left:50%;bottom:20px;transform:translateX(-50%);padding:10px 16px;font-weight:850}.wfHot{right:20px;bottom:20px;padding:10px 14px}.wfHot a{color:#cfe9ff}.wfMsg{left:50%;top:72%;transform:translateX(-50%);max-width:720px;padding:14px 18px;font-weight:800;text-align:center;opacity:0;transition:.2s}.wfMsg.show{opacity:1}.wfMini{right:18px;top:86px;width:190px;height:140px;padding:8px}.wfMini canvas{width:100%;height:100%;border-radius:12px;background:#0b1a16}.wfPrompt{position:absolute;pointer-events:none;background:rgba(16,13,7,.88);border:1px solid #e6c46a;color:#fff2b8;border-radius:999px;padding:8px 12px;font-weight:900;transform:translate(-50%,-130%);white-space:nowrap}.wfTools{position:absolute;right:18px;top:250px;display:flex;flex-direction:column;gap:8px;pointer-events:auto}.wfTools button{border:1px solid #425166;background:#111927;color:#d8ebff;border-radius:12px;padding:9px 12px;font-weight:900}.wfTools button.on{border-color:#f4ce68;color:#ffe9a6}`;document.head.appendChild(st)}
function mount(){inject();var r=document.createElement('div');r.className='wfRoot';r.innerHTML='<canvas class="wfCanvas"></canvas><div class="wfHud"><div class="wfPanel wfTop"><h1 id="wfTitle">Whisperwind</h1><p id="wfSub">Composer-rendered scene</p></div><button class="wfClose" id="wfClose">Leave</button><div class="wfPanel wfMini"><canvas id="wfMini"></canvas></div><div class="wfTools"><button id="wfDebug">Boundaries</button><button onclick="location.href=\'/games/world_composer.html\'">Composer</button></div><div id="wfPrompt" class="wfPrompt" style="display:none"></div><div class="wfPanel wfMsg" id="wfMsg"></div><div class="wfPanel wfHint">WASD / arrows to move · Press E near prompts · Mouse wheel zoom</div><div class="wfPanel wfHot">Editor: <a href="/games/world_composer.html">World Composer</a></div></div>';document.body.appendChild(r);E.root=r;E.canvas=r.querySelector('canvas');E.ctx=E.canvas.getContext('2d');$('#wfClose').onclick=()=>{if(E.onClose)E.onClose();else location.href='/'};$('#wfDebug').onclick=function(){E.debug=!E.debug;this.classList.toggle('on',E.debug)};window.addEventListener('resize',resize);window.addEventListener('keydown',key,true);window.addEventListener('keyup',key,true);E.canvas.addEventListener('wheel',function(ev){ev.preventDefault();E.cam.zoom=Math.max(.55,Math.min(1.8,E.cam.zoom+(ev.deltaY<0?.08:-.08)))},{passive:false});resize()}
function start(o){o=o||{};E.username=o.username||'Wanderer';E.onClose=o.onClose;mount();Promise.all([loadJson('/assets/worlds/'+(o.sceneId||'whisperwind_composer_recovery')+'.json').catch(()=>loadJson('/assets/worlds/whisperwind_composer_recovery.json')),loadJson('/assets/worlds/world_asset_catalog.json').catch(()=>loadJson('/data/world_asset_catalog.json')).catch(()=>({assets:[]}))]).then(([sc,cat])=>{E.scene=sc;E.catalog={};(cat.assets||[]).forEach(a=>E.catalog[a.id]=a);$('#wfTitle').textContent=sc.name||'Whisperwind';$('#wfSub').textContent='Soft paths · object scene · no giant filled road polygons';var p=sc.spawn||{};E.player.x=p.x||900;E.player.y=p.y||720;var list=[];(sc.objects||[]).forEach(o=>{var a=E.catalog[o.asset];if(a&&a.src)list.push(img(a.src))});if(sc.playerSprite)list.push(img(sc.playerSprite));return Promise.all(list)}).then(()=>{E.last=performance.now();toast('Recovery scene loaded. This is the new object/composer renderer.');loop(E.last)}).catch(err=>{document.body.innerHTML='<pre style="color:white;padding:20px">World load failed: '+err.message+'</pre>'})}
function resize(){if(!E.canvas)return;E.canvas.width=innerWidth*devicePixelRatio;E.canvas.height=innerHeight*devicePixelRatio;E.canvas.style.width=innerWidth+'px';E.canvas.style.height=innerHeight+'px';E.ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
function key(ev){var down=ev.type==='keydown';var k=ev.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d','e','b'].includes(k)){if(k==='e'&&down){interact();ev.preventDefault();return}if(k==='b'&&down){E.debug=!E.debug;var b=$('#wfDebug');if(b)b.classList.toggle('on',E.debug);return}E.keys[k]=down;ev.preventDefault()}}
function loop(t){var dt=Math.min(.033,(t-E.last)/1000||.016);E.last=t;update(dt);render(t/1000);E.raf=requestAnimationFrame(loop)}
function update(dt){var ax=0,ay=0;if(E.keys.w||E.keys.arrowup)ay-=1;if(E.keys.s||E.keys.arrowdown)ay+=1;if(E.keys.a||E.keys.arrowleft)ax-=1;if(E.keys.d||E.keys.arrowright)ax+=1;var len=Math.hypot(ax,ay)||1;ax/=len;ay/=len;var speed=260;var tx=ax*speed,ty=ay*speed;E.player.vx+=(tx-E.player.vx)*Math.min(1,dt*12);E.player.vy+=(ty-E.player.vy)*Math.min(1,dt*12);var nx=E.player.x+E.player.vx*dt,ny=E.player.y+E.player.vy*dt;if(canStand(nx,ny)){E.player.x=nx;E.player.y=ny}else{E.player.vx*=.15;E.player.vy*=.15}E.player.moving=Math.hypot(E.player.vx,E.player.vy)>18;if(Math.abs(E.player.vx)>Math.abs(E.player.vy))E.player.face=E.player.vx<0?'left':'right';else if(Math.abs(E.player.vy)>8)E.player.face=E.player.vy<0?'up':'down';var sw=E.scene&&E.scene.size?E.scene.size.w:1800,sh=E.scene&&E.scene.size?E.scene.size.h:1200;var targetX=E.player.x-innerWidth/(2*E.cam.zoom),targetY=E.player.y-innerHeight/(2*E.cam.zoom);E.cam.x+=(targetX-E.cam.x)*Math.min(1,dt*6);E.cam.y+=(targetY-E.cam.y)*Math.min(1,dt*6);E.cam.x=Math.max(0,Math.min(sw-innerWidth/E.cam.zoom,E.cam.x));E.cam.y=Math.max(0,Math.min(sh-innerHeight/E.cam.zoom,E.cam.y));findNear();if(E.msgTimer>0){E.msgTimer-=dt;if(E.msgTimer<=0)$('#wfMsg').classList.remove('show')}}
function canStand(x,y){var sc=E.scene;if(!sc)return true;for(var o of (sc.objects||[])){if(!o.collide)continue;var c=o.collide;var rx=o.x+c[0]*(o.scale||1),ry=o.y+c[1]*(o.scale||1),rw=c[2]*(o.scale||1),rh=c[3]*(o.scale||1);if(x>rx&&x<rx+rw&&y>ry&&y<ry+rh)return false}return x>10&&y>10&&x<(sc.size.w-10)&&y<(sc.size.h-10)}
function findNear(){E.near=null;var best=1e9;var all=[...(E.scene.hotspots||[]),...(E.scene.npcs||[])];for(var h of all){var d=Math.hypot(E.player.x-h.x,E.player.y-h.y);if(d<(h.r||70)&&d<best){best=d;E.near=h}}var p=$('#wfPrompt');if(E.near){var sp=worldToScreen(E.near.x,E.near.y);p.style.left=sp.x+'px';p.style.top=sp.y+'px';p.style.display='block';p.textContent='E · '+(E.near.label||E.near.name||'Interact')}else p.style.display='none'}
function interact(){if(!E.near){toast('Nothing close enough.');return}toast(E.near.message||((E.near.name||E.near.label)+': Hello.'))}
function toast(s){var m=$('#wfMsg');m.textContent=s;m.classList.add('show');E.msgTimer=4}
function worldToScreen(x,y){return{x:(x-E.cam.x)*E.cam.zoom,y:(y-E.cam.y)*E.cam.zoom}}
function tx(){E.ctx.setTransform(devicePixelRatio*E.cam.zoom,0,0,devicePixelRatio*E.cam.zoom,-E.cam.x*devicePixelRatio*E.cam.zoom,-E.cam.y*devicePixelRatio*E.cam.zoom)}
function reset(){E.ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
function render(time){var c=E.ctx,sc=E.scene;if(!sc)return;reset();c.clearRect(0,0,innerWidth,innerHeight);tx();drawTerrain(c,sc,time);drawObjects(c,sc,'structures');drawObjects(c,sc,'buildings');drawNpcs(c,sc,time);drawPlayer(c,time);drawObjects(c,sc,'props');drawObjects(c,sc,'canopy');drawHotspots(c,sc);if(E.debug)drawDebug(c,sc);reset();drawMini()}
function drawTerrain(c,sc,time){var w=sc.size.w,h=sc.size.h;var g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,'#234f2d');g.addColorStop(.55,'#356b37');g.addColorStop(1,'#1c432b');c.fillStyle=g;c.fillRect(0,0,w,h);c.globalAlpha=.12;for(var i=0;i<900;i++){var x=(i*73)%w,y=(i*149)%h;c.fillStyle=i%4?'#102414':'#d7c36a';c.fillRect(x,y,2+(i%3),2)}c.globalAlpha=1;(sc.terrain&&sc.terrain.water||[]).forEach(wat=>{path(c,wat.points);c.fillStyle='#17556c';c.fill();c.strokeStyle='#79d8de88';c.lineWidth=4;for(var j=0;j<8;j++){c.beginPath();for(var p=0;p<wat.points.length;p++){var pt=wat.points[p];c[p?'lineTo':'moveTo'](pt[0]+Math.sin(time+j+p)*8,pt[1]+Math.cos(time*.6+j+p)*6)}c.stroke()}});(sc.paths||[]).forEach(p=>drawSoftPath(c,p,time))}
function drawSoftPath(c,p,time){var pts=p.points||[];if(pts.length<2)return;c.save();c.lineCap='round';c.lineJoin='round';c.strokeStyle=p.kind==='plaza'?'#9c8861':'#91754c';c.lineWidth=p.width||90;c.globalAlpha=.96;c.beginPath();pts.forEach((pt,i)=>i?c.lineTo(pt[0],pt[1]):c.moveTo(pt[0],pt[1]));c.stroke();c.strokeStyle='rgba(54,40,24,.22)';c.lineWidth=(p.width||90)+10;c.stroke();c.globalAlpha=.26;c.strokeStyle='#d7c294';c.lineWidth=(p.width||90)*.42;c.stroke();c.globalAlpha=.35;for(var i=0;i<35;i++){var a=pts[i%pts.length],b=pts[(i+1)%pts.length]||a;var t=(i*37%100)/100;var x=a[0]+(b[0]-a[0])*t+(i%7-3)*9,y=a[1]+(b[1]-a[1])*t+(i%5-2)*9;c.fillStyle=i%2?'#4c3d2b':'#d4c08d';c.beginPath();c.ellipse(x,y,2+i%4,1+i%3,0,0,7);c.fill()}c.restore()}
function drawObjects(c,sc,layer){(sc.objects||[]).filter(o=>(o.layer||'props')===layer).sort((a,b)=>a.y-b.y).forEach(o=>{var a=E.catalog[o.asset],im=a&&E.assets[a.src];if(!im)return;c.save();c.translate(o.x,o.y);if(o.rotation)c.rotate(o.rotation);var s=o.scale||1;c.scale(s,s);c.drawImage(im,-im.width/2,-im.height);c.restore()})}
function drawNpcs(c,sc,time){(sc.npcs||[]).forEach(n=>{c.save();c.translate(n.x,n.y);c.fillStyle='rgba(0,0,0,.28)';c.beginPath();c.ellipse(0,8,18,7,0,0,7);c.fill();c.fillStyle='#f2c35a';c.strokeStyle='#3b250d';c.lineWidth=3;c.beginPath();c.roundRect(-15,-38,30,42,10);c.fill();c.stroke();c.fillStyle='#fff';c.font='bold 13px system-ui';c.textAlign='center';c.strokeStyle='#000';c.lineWidth=4;c.strokeText(n.name||'NPC',0,-48);c.fillText(n.name||'NPC',0,-48);c.restore()})}
function drawPlayer(c,time){var x=E.player.x,y=E.player.y;c.save();c.translate(x,y);c.fillStyle='rgba(0,0,0,.32)';c.beginPath();c.ellipse(0,10,20,8,0,0,7);c.fill();c.fillStyle='#4ba3ff';c.strokeStyle='#062033';c.lineWidth=3;c.beginPath();c.roundRect(-16,-48,32,52,11);c.fill();c.stroke();c.fillStyle='#ffe4b8';c.beginPath();c.arc(0,-57,14,0,7);c.fill();c.fillStyle='#fff';c.font='bold 13px system-ui';c.textAlign='center';c.strokeStyle='#000';c.lineWidth=4;c.strokeText(E.username,0,-78);c.fillText(E.username,0,-78);c.restore()}
function drawHotspots(c,sc){if(!E.near)return;c.save();c.strokeStyle='#ffe58a';c.fillStyle='rgba(255,220,92,.13)';c.lineWidth=3;c.beginPath();c.arc(E.near.x,E.near.y,E.near.r||70,0,7);c.fill();c.stroke();c.restore()}
function path(c,pts){c.beginPath();pts.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.closePath()}
function drawDebug(c,sc){c.save();c.strokeStyle='#ff4d6d';c.lineWidth=2;(sc.objects||[]).forEach(o=>{if(o.collide){var cc=o.collide,s=o.scale||1;c.strokeRect(o.x+cc[0]*s,o.y+cc[1]*s,cc[2]*s,cc[3]*s)}});c.strokeStyle='#64e3ff';(sc.paths||[]).forEach(p=>{c.beginPath();p.points.forEach((pt,i)=>i?c.lineTo(pt[0],pt[1]):c.moveTo(pt[0],pt[1]));c.stroke()});c.restore()}
function drawMini(){var m=$('#wfMini'),c=m.getContext('2d'),sc=E.scene;if(!sc)return;m.width=190*devicePixelRatio;m.height=140*devicePixelRatio;c.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);c.clearRect(0,0,190,140);var sx=190/sc.size.w,sy=140/sc.size.h;c.fillStyle='#10281c';c.fillRect(0,0,190,140);c.fillStyle='#8d744c';(sc.paths||[]).forEach(p=>{c.lineCap='round';c.lineJoin='round';c.strokeStyle='#8d744c';c.lineWidth=(p.width||80)*sx;c.beginPath();p.points.forEach((pt,i)=>i?c.lineTo(pt[0]*sx,pt[1]*sy):c.moveTo(pt[0]*sx,pt[1]*sy));c.stroke()});c.fillStyle='#5ecbff';c.beginPath();c.arc(E.player.x*sx,E.player.y*sy,4,0,7);c.fill()}
window.WorldForgerEngine={start:start};window.PetWorldWorldEngine={start:start};
})();
