/*
  GameForge AI - World Forger Town Engine v1
  A playable multiplayer JRPG-style town hub with housing ownership.
  Vanilla JS only. Data-first design so JSON storage can move to DB later.
*/
(function(){
'use strict';
var ASSET='/assets/worldkit/whisperwind/';
var CFG_URL='/assets/worlds/whisperwind_village.json';
var ESTATE_ID='whisperwind_01';
var W=5200,H=4200;
var defaultScene={id:'whisperwind_village',name:'Whisperwind Village',spawn:{x:2600,y:2760,face:'down'},objects:[],houses:[],npcs:[]};
var state={root:null,canvas:null,ctx:null,ui:null,scene:defaultScene,estate:null,images:{},running:false,last:0,username:'guest',onClose:null,keys:{},player:{x:2600,y:2760,face:'down',moving:false,speed:265,step:0,color:'#56d8ff'},camera:{x:0,y:0,scale:1},hover:null,dialog:null,toastTimer:0,remote:{ws:null,id:'',peers:{},lastSent:0,connected:false},inside:null};
function $(id){return document.getElementById(id);}function clamp(v,a,b){return Math.max(a,Math.min(b,v));}function dist(a,b,c,d){var x=a-c,y=b-d;return Math.sqrt(x*x+y*y);}function esc(s){return String(s||'').replace(/[&<>\"]/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m];});}
function mount(){if(state.root)return;injectStyles();var root=document.createElement('div');root.id='gfTownRoot';root.innerHTML='<canvas id="gfTownCanvas"></canvas><div id="gfTownUi"><div class="top"><div class="brand"><b>Whisperwind Village</b><span id="gfTownSub">living town prototype</span></div><div class="net" id="gfTownNet">🌐 connecting</div><button id="gfTownLeave">Leave</button></div><div class="hint" id="gfTownHint">WASD / arrows to move · E to interact · H homes · M map</div><div class="panel hidden" id="gfTownPanel"></div><div class="toast" id="gfTownToast"></div><div class="interact hidden" id="gfTownInteract"></div><div class="map hidden" id="gfTownMap"></div></div>';document.body.appendChild(root);state.root=root;state.canvas=$('gfTownCanvas');state.ctx=state.canvas.getContext('2d');$('gfTownLeave').onclick=stop;window.addEventListener('resize',resize);window.addEventListener('keydown',keyDown,true);window.addEventListener('keyup',keyUp,true);state.canvas.addEventListener('pointerdown',pointerDown);resize();}
function injectStyles(){var css='html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#071018}#gfTownRoot{position:fixed;inset:0;background:#071018;color:#eaf7ff;font-family:Inter,system-ui,Segoe UI,Arial,sans-serif}#gfTownCanvas{position:absolute;inset:0;width:100%;height:100%;image-rendering:auto}.top{position:absolute;left:14px;right:14px;top:12px;display:flex;gap:10px;align-items:center;pointer-events:none}.brand,.net,.hint,.panel,.toast,.interact,.map{background:linear-gradient(180deg,rgba(10,25,38,.94),rgba(5,13,22,.90));border:1px solid rgba(91,211,255,.28);box-shadow:0 12px 40px rgba(0,0,0,.32);backdrop-filter:blur(10px)}.brand{padding:10px 13px;border-radius:16px;min-width:240px}.brand b{display:block;font-size:17px}.brand span{display:block;color:#a7c8dc;font-size:12px;margin-top:2px}.net{padding:9px 12px;border-radius:999px;color:#bcefff;font-weight:800;font-size:12px}#gfTownLeave{margin-left:auto;pointer-events:auto;border:1px solid rgba(91,211,255,.32);background:#0b1c2b;color:#fff;border-radius:14px;padding:10px 14px;font-weight:900;cursor:pointer}.hint{position:absolute;left:14px;bottom:14px;padding:10px 13px;border-radius:999px;color:#d9f4ff;font-size:12px;font-weight:800}.toast{position:absolute;left:50%;bottom:62px;transform:translateX(-50%);padding:11px 16px;border-radius:999px;opacity:0;transition:.2s;font-weight:900;max-width:min(720px,90vw);text-align:center}.toast.show{opacity:1}.interact{position:absolute;left:50%;bottom:106px;transform:translateX(-50%);padding:12px 16px;border-radius:16px;font-weight:900;text-align:center}.interact small{display:block;color:#a7c8dc;margin-top:3px}.panel{position:absolute;right:16px;top:72px;width:min(390px,calc(100vw - 32px));max-height:calc(100vh - 115px);overflow:auto;border-radius:20px;padding:14px}.panel h2{margin:0 0 8px;font-size:19px}.panel p{color:#b9d2df;line-height:1.35}.panel .card{border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.045);border-radius:16px;padding:11px;margin:9px 0}.panel button{border:1px solid rgba(91,211,255,.35);background:#10283a;color:#fff;border-radius:12px;padding:9px 11px;font-weight:900;cursor:pointer;margin:3px}.panel button.primary{background:linear-gradient(180deg,#187aa1,#0e4e71);border-color:#6bdcff}.panel button.danger{background:#3a1723;border-color:#d66b82}.owner{color:#92f7ad;font-weight:900}.available{color:#f8d276;font-weight:900}.map{position:absolute;left:16px;top:72px;width:260px;border-radius:18px;padding:12px}.map h3{margin:0 0 8px}.map div{font-size:12px;color:#b9d2df;margin:4px 0}.hidden{display:none!important}@media(max-width:760px){.top{left:8px;right:8px;top:8px}.brand{min-width:0;padding:8px 10px}.brand b{font-size:14px}.net{display:none}.hint{left:8px;right:8px;text-align:center;border-radius:14px}.panel{right:8px;left:8px;top:62px;width:auto}.map{left:8px;right:8px;width:auto}}';var s=document.createElement('style');s.textContent=css;document.head.appendChild(s);}
function start(opts){mount();opts=opts||{};state.username=opts.username||'guest';state.onClose=opts.onClose||null;Promise.all([loadScene(),loadEstate()]).then(function(){var sp=state.scene.spawn||defaultScene.spawn;state.player.x=sp.x;state.player.y=sp.y;state.player.face=sp.face||'down';state.running=true;state.last=performance.now();connectSocket();toast('Welcome to Whisperwind. Explore the upper town, market, tavern, docks, and homes.');requestAnimationFrame(loop);});}
function stop(){try{if(state.remote.ws&&state.remote.ws.readyState===1)state.remote.ws.send(JSON.stringify({type:'worldLeave'}));}catch(e){}state.running=false;if(state.root)state.root.remove();state.root=null;if(state.onClose)state.onClose();}
function loadScene(){return fetch(CFG_URL+'?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.json();}).then(function(j){state.scene=normalizeScene(j||defaultScene);preload();}).catch(function(){state.scene=normalizeScene(defaultScene);});}
function loadEstate(){return fetch('/api/estate/neighborhoods/'+ESTATE_ID+'?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.json();}).then(function(j){state.estate=j.neighborhood||null;}).catch(function(){state.estate=null;});}
function normalizeScene(s){s=s||{};s.objects=s.objects||[];s.decorations=s.decorations||[];s.npcs=s.npcs||[];s.houses=s.houses||s.plots||[];s.interiors=s.interiors||{};return Object.assign({},defaultScene,s);}
function preload(){var urls={};function add(u){if(u)urls[u]=true;}add(ASSET+'starter_cottage_gameforge.png');add(ASSET+'general_store_gameforge.png');add(ASSET+'echo_hall_gameforge.png');add(ASSET+'tree_oak_gameforge.png');add(ASSET+'fountain_gameforge.png');add(ASSET+'dock_gameforge.png');add(ASSET+'town_board_gameforge.png');add(ASSET+'lamp_gameforge.png');add(ASSET+'bench_gameforge.png');add(ASSET+'flowers_blue.png');add(ASSET+'flowers_gold.png');add(ASSET+'flowers_pink.png');(state.scene.objects||[]).concat(state.scene.decorations||[]).forEach(function(o){add(o.asset);});Object.keys(urls).forEach(function(u){var im=new Image();im.onload=function(){state.images[u]=im;};im.src=u;});}
function resize(){if(!state.canvas)return;var d=window.devicePixelRatio||1;state.canvas.width=Math.floor(innerWidth*d);state.canvas.height=Math.floor(innerHeight*d);state.canvas.style.width=innerWidth+'px';state.canvas.style.height=innerHeight+'px';state.ctx.setTransform(d,0,0,d,0,0);}
function keyDown(e){var k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d','e','h','m','escape'].indexOf(k)>=0)e.preventDefault();if(k==='e')interact();else if(k==='h')showHomes();else if(k==='m')toggleMap();else if(k==='escape')closePanels();state.keys[k]=true;}
function keyUp(e){state.keys[e.key.toLowerCase()]=false;}
function pointerDown(ev){var p=screenToWorld(ev.clientX,ev.clientY);state.player.target=p;}
function screenToWorld(x,y){return {x:(x-state.camera.x)/state.camera.scale,y:(y-state.camera.y)/state.camera.scale};}
function loop(t){if(!state.running)return;var dt=Math.min(.04,(t-state.last)/1000||0);state.last=t;update(dt);draw();requestAnimationFrame(loop);}
function update(dt){var p=state.player,dx=0,dy=0;if(state.keys.w||state.keys.arrowup)dy-=1;if(state.keys.s||state.keys.arrowdown)dy+=1;if(state.keys.a||state.keys.arrowleft)dx-=1;if(state.keys.d||state.keys.arrowright)dx+=1;if(p.target&&!dx&&!dy){var tx=p.target.x-p.x,ty=p.target.y-p.y,dd=Math.sqrt(tx*tx+ty*ty);if(dd>8){dx=tx/dd;dy=ty/dd;}else p.target=null;}if(dx||dy){var l=Math.sqrt(dx*dx+dy*dy);dx/=l;dy/=l;if(Math.abs(dx)>Math.abs(dy))p.face=dx>0?'right':'left';else p.face=dy>0?'down':'up';var nx=p.x+dx*p.speed*dt,ny=p.y+dy*p.speed*dt;if(canStand(nx,p.y))p.x=nx;if(canStand(p.x,ny))p.y=ny;p.moving=true;p.step+=dt*10;}else{p.moving=false;p.step+=dt*2;}p.x=clamp(p.x,80,W-80);p.y=clamp(p.y,80,H-80);state.hover=findInteraction();updateCamera();sendPosition(false);}
function updateCamera(){var sc=clamp(Math.min(innerWidth/1120,innerHeight/720),.72,1.18);state.camera.scale=sc;state.camera.x=innerWidth/2-state.player.x*sc;state.camera.y=innerHeight/2-state.player.y*sc;state.camera.x=clamp(state.camera.x,innerWidth-W*sc,0);state.camera.y=clamp(state.camera.y,innerHeight-H*sc,0);if(W*sc<innerWidth)state.camera.x=(innerWidth-W*sc)/2;if(H*sc<innerHeight)state.camera.y=(innerHeight-H*sc)/2;var inter=$('gfTownInteract');if(state.hover){inter.classList.remove('hidden');inter.innerHTML='Press E · '+esc(state.hover.label||state.hover.name||'Interact')+'<small>'+esc(state.hover.kind||'')+'</small>';}else inter.classList.add('hidden');$('gfTownNet').textContent=state.remote.connected?'🌐 online · '+(Object.keys(state.remote.peers).length+1)+' here':'🌐 offline town';}
function canStand(x,y){if(x<50||y<50||x>W-50||y>H-50)return false;if(inPoly(x,y,[[4400,0],[5200,0],[5200,4200],[4160,4200],[4300,3600],[4240,3200],[4450,2830],[4380,2300],[4590,1750],[4430,1160]]))return false;if(inPoly(x,y,[[0,0],[1050,0],[960,340],[690,560],[250,690],[0,640]]))return false;var solids=solidRects();for(var i=0;i<solids.length;i++){var r=solids[i];if(x>r.x&&x<r.x+r.w&&y>r.y&&y<r.y+r.h)return false;}return true;}
function solidRects(){var a=[];allObjects().forEach(function(o){if(o.solid){a.push({x:o.x+(o.solid.x||0),y:o.y+(o.solid.y||0),w:o.solid.w||100,h:o.solid.h||80});}});houses().forEach(function(h){a.push({x:h.houseX-150,y:h.houseY-210,w:300,h:170});});return a;}
function inPoly(x,y,poly){var inside=false;for(var i=0,j=poly.length-1;i<poly.length;j=i++){var xi=poly[i][0],yi=poly[i][1],xj=poly[j][0],yj=poly[j][1];var intersect=((yi>y)!=(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi)+xi);if(intersect)inside=!inside;}return inside;}
function allObjects(){return (state.scene.objects||[]).concat(state.scene.decorations||[]);}function houses(){return state.scene.houses||[];}
function findInteraction(){var best=null,bd=999999;function check(obj,kind,label,x,y,r){var d=dist(state.player.x,state.player.y,x,y);if(d<(r||130)&&d<bd){bd=d;best=Object.assign({},obj,{kind:kind,label:label||obj.label||obj.name,x:x,y:y});}}allObjects().forEach(function(o){if(o.interact)check(o,o.interact.kind,o.interact.label,o.x,o.y,o.interact.radius||150);});houses().forEach(function(h){check(h,'house',houseLabel(h),h.houseX,h.houseY+15,170);});(state.scene.npcs||[]).forEach(function(n){check(n,'npc','Talk to '+n.name,n.x,n.y,115);});return best;}
function estatePlot(id){var e=state.estate;if(!e)return null;return (e.plots||[]).find(function(p){return p.id===id;})||null;}function houseLabel(h){var p=estatePlot(h.id);return p&&p.owner?'Visit '+p.owner+'\'s '+(p.name||'Cottage'):'Claim '+(h.name||'Cottage');}
function interact(){var h=state.hover;if(!h){toast('Nothing nearby to interact with.');return;}if(h.kind==='npc'){showDialogue(h.name,h.dialogue||['Hello there.']);return;}if(h.kind==='shop'){showShop(h);return;}if(h.kind==='tavern'){showDialogue('The Blue Lantern Tavern',['Warm light, clinking mugs, and a rumor board. This should become the social matchmaking room for quests, parties, and mini-games.']);return;}if(h.kind==='enter'){showDialogue(h.interact&&h.interact.label||h.name,[h.interact&&h.interact.message||'This interior is being prepared.']);return;}if(h.kind==='fish'){toast('Fishing dock found. This can route into the existing fishing system next.');return;}if(h.kind==='read'||h.kind==='inspect'||h.kind==='travel'){showDialogue(h.interact&&h.interact.label||h.name,[(h.interact&&h.interact.message)||h.message||'Interesting.']);return;}if(h.kind==='house'){showHouse(h);return;}toast(h.label||'Interacted.');}
function closePanels(){$('gfTownPanel').classList.add('hidden');$('gfTownMap').classList.add('hidden');}
function panel(html){var p=$('gfTownPanel');p.innerHTML=html;p.classList.remove('hidden');}
function showDialogue(title,lines){lines=Array.isArray(lines)?lines:[String(lines||'')];panel('<h2>'+esc(title||'Dialogue')+'</h2>'+lines.map(function(l){return '<p>'+esc(l)+'</p>';}).join('')+'<button onclick="document.getElementById(\'gfTownPanel\').classList.add(\'hidden\')">Close</button>');}
function showShop(o){panel('<h2>'+esc(o.name||'General Store')+'</h2><p>The shop counter is ready. Next step is wiring this to your existing item/shop catalog.</p><div class="card"><b>Planned stock</b><p>Bait, furniture permits, house decorations, pet care items, town project supplies.</p></div><button>Browse Soon</button><button onclick="document.getElementById(\'gfTownPanel\').classList.add(\'hidden\')">Close</button>');}
function showHouse(h){var p=estatePlot(h.id)||{};var owner=p.owner||'';var mine=owner&&owner.toLowerCase()===state.username.toLowerCase();var html='<h2>'+esc(h.name||p.name||'Cottage')+'</h2><div class="card"><b>Status:</b> '+(owner?'<span class="owner">Owned by '+esc(owner)+'</span>':'<span class="available">Available</span>')+'</div><p>'+esc(h.description||'A cozy starter cottage in Whisperwind Village.')+'</p>';if(!owner){html+='<button class="primary" id="claimHouseBtn">Claim this house</button>';}else{html+='<button class="primary" id="enterHouseBtn">Enter cottage</button>';if(mine)html+='<button class="danger" id="sellHouseBtn">Sell / release house</button>';}html+='<button onclick="document.getElementById(\'gfTownPanel\').classList.add(\'hidden\')">Close</button>';panel(html);var c=$('claimHouseBtn');if(c)c.onclick=function(){claimHouse(h.id);};var s=$('sellHouseBtn');if(s)s.onclick=function(){sellHouse(h.id);};var e=$('enterHouseBtn');if(e)e.onclick=function(){enterHouse(h,p);};}
function enterHouse(h,p){panel('<h2>'+esc((p.owner||'Starter')+' Cottage')+'</h2><p>You step inside. This is the interior hook: furniture placement, storage, trophies, pets, and visitors should live here.</p><div class="card"><b>Interior v1</b><p>Owner: '+esc(p.owner||'None')+'<br>Privacy: '+esc(p.privacy||'public')+'<br>House type: '+esc(p.houseType||'starter_cottage')+'</p></div><button onclick="document.getElementById(\'gfTownPanel\').classList.add(\'hidden\')">Exit Cottage</button>');}
function claimHouse(plotId){fetch('/api/estate/neighborhoods/'+ESTATE_ID+'/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:state.username,plotId:plotId})}).then(function(r){return r.json();}).then(function(j){if(!j.ok)throw new Error(j.error||'Could not claim house');state.estate=j.neighborhood;toast('House claimed. Welcome home, '+state.username+'!');showHouse((houses().find(function(h){return h.id===plotId;})||{id:plotId}));}).catch(function(e){toast(e.message||'Could not claim house');});}
function sellHouse(plotId){fetch('/api/estate/neighborhoods/'+ESTATE_ID+'/sell',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:state.username,plotId:plotId})}).then(function(r){return r.json();}).then(function(j){if(!j.ok)throw new Error(j.error||'Could not sell house');state.estate=j.neighborhood;toast('House released for resale.');showHouse((houses().find(function(h){return h.id===plotId;})||{id:plotId}));}).catch(function(e){toast(e.message||'Could not sell house');});}
function showHomes(){var html='<h2>Available Housing</h2><p>Choose one cottage to live in. Later this can become buying/selling with coins and furniture value.</p>';houses().forEach(function(h){var p=estatePlot(h.id)||{};html+='<div class="card"><b>'+esc(h.name||p.name||h.id)+'</b><br>'+(p.owner?'<span class="owner">Owned by '+esc(p.owner)+'</span>':'<span class="available">Available</span>')+'<br><button data-house="'+esc(h.id)+'">View</button></div>';});html+='<button onclick="document.getElementById(\'gfTownPanel\').classList.add(\'hidden\')">Close</button>';panel(html);document.querySelectorAll('[data-house]').forEach(function(b){b.onclick=function(){showHouse(houses().find(function(h){return h.id===b.getAttribute('data-house');})||{});};});}
function toggleMap(){var m=$('gfTownMap');if(!m.classList.contains('hidden')){m.classList.add('hidden');return;}m.innerHTML='<h3>Whisperwind Map</h3><div>▲ Upper town: Echo Hall + overlook</div><div>◆ Mid town: plaza + fountain</div><div>◄ West: market + tavern</div><div>► East: board + homes</div><div>▼ South: docks + river</div><div>H: housing list</div>';m.classList.remove('hidden');}
function toast(t){var el=$('gfTownToast');el.textContent=t;el.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(function(){el.classList.remove('show');},2600);}
function draw(){var ctx=state.ctx;if(!ctx)return;ctx.clearRect(0,0,innerWidth,innerHeight);ctx.save();ctx.translate(state.camera.x,state.camera.y);ctx.scale(state.camera.scale,state.camera.scale);drawWorld(ctx);ctx.restore();}
function drawWorld(ctx){drawGround(ctx);var drawables=[];allObjects().forEach(function(o){drawables.push(Object.assign({drawType:'obj'},o));});houses().forEach(function(h){drawables.push(Object.assign({drawType:'house'},h));});(state.scene.npcs||[]).forEach(function(n){drawables.push(Object.assign({drawType:'npc'},n));});Object.keys(state.remote.peers).forEach(function(id){drawables.push(Object.assign({drawType:'remote'},state.remote.peers[id]));});drawables.push({drawType:'player',x:state.player.x,y:state.player.y});drawables.sort(function(a,b){return (a.y||0)-(b.y||0);});drawables.forEach(function(o){if(o.drawType==='house')drawHouse(ctx,o);else if(o.drawType==='npc')drawNpc(ctx,o);else if(o.drawType==='remote')drawRemote(ctx,o);else if(o.drawType==='player')drawPlayer(ctx,state.player,true);else drawObject(ctx,o);});drawEffects(ctx);}
function drawGround(ctx){var g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#2f6a45');g.addColorStop(.55,'#3d7b4c');g.addColorStop(1,'#25573d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);drawPoly(ctx,[[4400,0],[5200,0],[5200,4200],[4160,4200],[4300,3600],[4240,3200],[4450,2830],[4380,2300],[4590,1750],[4430,1160]],'#226e8c','#39b8d8');drawPoly(ctx,[[0,0],[1050,0],[960,340],[690,560],[250,690],[0,640]],'#216d87','#39b8d8');drawTerrace(ctx,2600,930,1500,720,'Upper Echo Terrace');drawTerrace(ctx,2600,2380,1760,1180,'Central Plaza');drawTerrace(ctx,1460,2290,950,760,'Market Lane');drawTerrace(ctx,3840,2000,1040,980,'Residential Rise');drawTerrace(ctx,3970,3420,1280,650,'River Dock');drawPath(ctx,[[2600,520],[2600,1100],[2600,1680],[2600,2380],[2600,3220],[2600,3900]],140);drawPath(ctx,[[1080,2380],[1600,2320],[2100,2360],[2600,2380],[3180,2350],[3720,2480],[4120,2640]],130);drawPath(ctx,[[1540,2380],[1240,1960],[1050,1510],[1030,1110]],105);drawPath(ctx,[[3570,2360],[3920,2000],[4100,1580],[4100,1110]],105);drawPath(ctx,[[3200,2850],[3600,3180],[4100,3460],[4620,3570]],115);drawPath(ctx,[[1980,2240],[2240,1960],[2600,1860],[2960,1960],[3220,2240],[3140,2620],[2800,2840],[2400,2840],[2060,2620],[1980,2240]],120,true);drawStairs(ctx,2600,1500,2600,1780);drawStairs(ctx,3420,2480,3640,2720);drawStairs(ctx,1790,2320,2040,2370);ctx.fillStyle='rgba(255,255,255,.06)';for(var i=0;i<140;i++){var x=(i*389)%W,y=(i*617)%H;if(canStand(x,y)){ctx.beginPath();ctx.arc(x,y,2+(i%3),0,Math.PI*2);ctx.fill();}}
}
function drawPoly(ctx,pts,fill,stroke){ctx.beginPath();pts.forEach(function(p,i){if(i)ctx.lineTo(p[0],p[1]);else ctx.moveTo(p[0],p[1]);});ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=12;ctx.globalAlpha=.55;ctx.stroke();ctx.globalAlpha=1;}
function drawTerrace(ctx,x,y,w,h,label){ctx.save();ctx.translate(x,y);ctx.fillStyle='rgba(20,60,45,.42)';roundRect(ctx,-w/2,-h/2,w,h,60);ctx.fill();ctx.strokeStyle='rgba(255,232,160,.20)';ctx.lineWidth=8;ctx.stroke();ctx.fillStyle='rgba(255,255,255,.11)';ctx.font='900 42px serif';ctx.textAlign='center';ctx.fillText(label,0,-h/2+72);ctx.restore();}
function drawPath(ctx,pts,width,closed){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#9b7147';ctx.lineWidth=width+20;ctx.globalAlpha=.36;ctx.beginPath();pts.forEach(function(p,i){if(i)ctx.lineTo(p[0],p[1]);else ctx.moveTo(p[0],p[1]);});if(closed)ctx.closePath();ctx.stroke();ctx.strokeStyle='#c49a61';ctx.lineWidth=width;ctx.globalAlpha=.98;ctx.stroke();ctx.strokeStyle='rgba(255,238,190,.23)';ctx.lineWidth=4;ctx.setLineDash([28,34]);ctx.stroke();ctx.restore();}
function drawStairs(ctx,x1,y1,x2,y2){ctx.save();ctx.strokeStyle='rgba(80,45,25,.45)';ctx.lineWidth=90;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.strokeStyle='rgba(245,218,160,.55)';ctx.lineWidth=8;for(var i=0;i<8;i++){var t=i/7,x=x1+(x2-x1)*t,y=y1+(y2-y1)*t;ctx.beginPath();ctx.moveTo(x-70,y);ctx.lineTo(x+70,y);ctx.stroke();}ctx.restore();}
function drawObject(ctx,o){var im=state.images[o.asset];shadow(ctx,o.x,o.y,(o.w||180)*.45,25);if(im){ctx.drawImage(im,o.x-(o.w||im.width)/2,o.y-(o.h||im.height),o.w||im.width,o.h||im.height);}else{ctx.fillStyle='#6b4a30';roundRect(ctx,o.x-60,o.y-120,120,120,10);ctx.fill();}if(state.hover&&state.hover.id===o.id)ring(ctx,o.x,o.y,80);}
function drawHouse(ctx,h){var p=estatePlot(h.id)||{};var im=state.images[h.asset||ASSET+'starter_cottage_gameforge.png'];shadow(ctx,h.houseX,h.houseY,170,34);if(im)ctx.drawImage(im,h.houseX-210,h.houseY-310,420,330);else{ctx.fillStyle='#8b5536';roundRect(ctx,h.houseX-140,h.houseY-210,280,190,14);ctx.fill();ctx.fillStyle='#5a2630';ctx.beginPath();ctx.moveTo(h.houseX-170,h.houseY-200);ctx.lineTo(h.houseX,h.houseY-340);ctx.lineTo(h.houseX+170,h.houseY-200);ctx.closePath();ctx.fill();}ctx.fillStyle=p.owner?'#98f7af':'#f7d06d';ctx.strokeStyle='rgba(0,0,0,.45)';ctx.lineWidth=5;ctx.font='900 36px Inter,Arial';ctx.textAlign='center';ctx.strokeText(p.owner?shortName(p.owner):'For Sale',h.houseX,h.houseY+28);ctx.fillText(p.owner?shortName(p.owner):'For Sale',h.houseX,h.houseY+28);if(state.hover&&state.hover.id===h.id)ring(ctx,h.houseX,h.houseY,120);}
function shortName(s){s=String(s||'');return s.length>12?s.slice(0,11)+'…':s;}
function drawNpc(ctx,n){shadow(ctx,n.x,n.y,42,14);ctx.fillStyle=n.color||'#f2c27b';ctx.beginPath();ctx.arc(n.x,n.y-56,28,0,Math.PI*2);ctx.fill();ctx.fillStyle=n.outfit||'#5bd8ff';roundRect(ctx,n.x-24,n.y-44,48,58,16);ctx.fill();ctx.fillStyle='#f7f2df';ctx.font='800 24px Inter';ctx.textAlign='center';ctx.fillText(n.name,n.x,n.y-88);if(state.hover&&state.hover.id===n.id)ring(ctx,n.x,n.y,62);}
function drawPlayer(ctx,p,me){drawAvatar(ctx,p.x,p.y,p.face,p.step,me?state.username:p.username,me?'#58d8ff':'#b38cff');}
function drawRemote(ctx,p){drawAvatar(ctx,p.x,p.y,p.face||'down',performance.now()/260,p.username||'Player','#b38cff');}
function drawAvatar(ctx,x,y,face,step,name,color){shadow(ctx,x,y,42,14);var bob=Math.sin(step)*4;ctx.fillStyle='#f0bd84';ctx.beginPath();ctx.arc(x,y-72+bob,27,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;roundRect(ctx,x-25,y-48+bob,50,62,18);ctx.fill();ctx.fillStyle='#3a2a1d';ctx.fillRect(x-24,y-92+bob,48,20);ctx.fillStyle='#14202b';ctx.fillRect(x-18,y+6+bob,14,42);ctx.fillRect(x+4,y+6+bob,14,42);ctx.fillStyle='#eaf7ff';ctx.font='900 25px Inter,Arial';ctx.textAlign='center';ctx.strokeStyle='rgba(0,0,0,.55)';ctx.lineWidth=5;ctx.strokeText(shortName(name),x,y-112);ctx.fillText(shortName(name),x,y-112);}
function drawEffects(ctx){var t=performance.now()/1000;ctx.save();ctx.globalAlpha=.28+.1*Math.sin(t*2);ctx.strokeStyle='#8df0ff';ctx.lineWidth=7;ctx.beginPath();ctx.arc(4540,3560,180+Math.sin(t)*20,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.22;for(var i=0;i<18;i++){ctx.fillStyle=i%2?'#ffe28a':'#7cf7ff';ctx.beginPath();ctx.arc(1800+(i*197)%1800,1100+(i*331)%2100+Math.sin(t+i)*18,4+(i%3),0,Math.PI*2);ctx.fill();}ctx.restore();}
function shadow(ctx,x,y,w,h){ctx.save();ctx.fillStyle='rgba(0,0,0,.22)';ctx.beginPath();ctx.ellipse(x,y,w,h,0,0,Math.PI*2);ctx.fill();ctx.restore();}
function ring(ctx,x,y,r){ctx.save();ctx.strokeStyle='#ffe38a';ctx.lineWidth=8;ctx.globalAlpha=.8;ctx.beginPath();ctx.ellipse(x,y,r,r*.38,0,0,Math.PI*2);ctx.stroke();ctx.restore();}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();}
function connectSocket(){try{var ws=new WebSocket((location.protocol==='https:'?'wss':'ws')+'://'+location.host);state.remote.ws=ws;ws.onopen=function(){state.remote.connected=true;sendJoin();};ws.onmessage=function(ev){handleSocket(ev.data);};ws.onclose=function(){state.remote.connected=false;setTimeout(function(){if(state.running)connectSocket();},1600);};ws.onerror=function(){state.remote.connected=false;};}catch(e){state.remote.connected=false;}}
function sendJoin(){var ws=state.remote.ws;if(ws&&ws.readyState===1)ws.send(JSON.stringify({type:'worldJoin',username:state.username,sceneId:state.scene.id||'whisperwind_village',x:state.player.x,y:state.player.y,face:state.player.face,moving:state.player.moving,mode:'town'}));}
function sendPosition(force){var ws=state.remote.ws;if(!ws||ws.readyState!==1)return;var now=performance.now();if(!force&&now-state.remote.lastSent<80)return;state.remote.lastSent=now;ws.send(JSON.stringify({type:'worldMove',x:Math.round(state.player.x),y:Math.round(state.player.y),face:state.player.face,moving:state.player.moving,mode:'town'}));}
function handleSocket(raw){var m;try{m=JSON.parse(raw);}catch(e){return;}if(m.type==='worldWelcome'){state.remote.id=m.id;state.remote.peers={};(m.peers||[]).forEach(function(p){state.remote.peers[p.id]=p;});return;}if(m.type==='worldJoin'&&m.player){state.remote.peers[m.player.id]=m.player;toast((m.player.username||'Someone')+' entered town.');return;}if(m.type==='worldMove'&&m.player){state.remote.peers[m.player.id]=m.player;return;}if(m.type==='worldLeave'){delete state.remote.peers[m.id];return;}}
window.GameForgeTownEngine={start:start,stop:stop};
})();
